import type { ExerciseLibraryEntry, MuscleGroup, Equipment } from '../types/workout';

// ── Category Labels ─────────────────────────────────────────────────

export const MUSCLE_GROUP_LABELS: Record<MuscleGroup, string> = {
  chest: 'Chest',
  back: 'Back',
  shoulders: 'Shoulders',
  legs: 'Legs',
  arms: 'Arms',
  core: 'Core',
  cardio: 'Cardio',
  full_body: 'Full Body',
};

export const EQUIPMENT_LABELS: Record<Equipment, string> = {
  barbell: 'Barbell',
  dumbbell: 'Dumbbell',
  machine: 'Machine',
  cable: 'Cable',
  bodyweight: 'Bodyweight',
  kettlebell: 'Kettlebell',
  band: 'Band',
};

export const EQUIPMENT_ICONS: Record<Equipment, string> = {
  barbell: 'barbell-outline',
  dumbbell: 'fitness-outline',
  machine: 'cog-outline',
  cable: 'git-pull-request-outline',
  bodyweight: 'body-outline',
  kettlebell: 'bowling-ball-outline',
  band: 'resize-outline',
};

// ── Exercise Library ────────────────────────────────────────────────

export const EXERCISE_LIBRARY: ExerciseLibraryEntry[] = [
  // ── CHEST ─────────────────────────────────────────────────────────
  {
    id: 'ex_bench_press',
    name: 'Barbell Bench Press',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoid', 'Triceps'],
    equipment: 'barbell',
    instructions: [
      'Lie flat on a bench with feet on the floor.',
      'Grip the bar slightly wider than shoulder width.',
      'Unrack and lower the bar to your mid-chest.',
      'Press the bar up to full lockout.',
    ],
    isCustom: false,
    defaultSets: 4,
    defaultReps: '6-10',
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_incline_bench',
    name: 'Incline Barbell Bench Press',
    category: 'chest',
    primaryMuscles: ['Upper Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoid', 'Triceps'],
    equipment: 'barbell',
    instructions: [
      'Set bench to 30-45 degree incline.',
      'Grip the bar slightly wider than shoulder width.',
      'Lower the bar to your upper chest.',
      'Press up to full lockout.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_bench_press',
    name: 'Dumbbell Bench Press',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoid', 'Triceps'],
    equipment: 'dumbbell',
    instructions: [
      'Lie flat on bench holding dumbbells at chest level.',
      'Press dumbbells up until arms are extended.',
      'Lower with control to chest level.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_flyes',
    name: 'Dumbbell Flyes',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoid'],
    equipment: 'dumbbell',
    instructions: [
      'Lie flat on bench with dumbbells above chest, palms facing in.',
      'Lower arms out to the sides with a slight bend in elbows.',
      'Squeeze chest to bring dumbbells back together.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-15',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_crossover',
    name: 'Cable Crossover',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoid'],
    equipment: 'cable',
    instructions: [
      'Set cables to high position, grab handles.',
      'Step forward, lean slightly.',
      'Bring handles together in front of chest with slight elbow bend.',
      'Slowly return to start.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_push_up',
    name: 'Push-Up',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoid', 'Triceps', 'Core'],
    equipment: 'bodyweight',
    instructions: [
      'Start in plank position with hands shoulder-width apart.',
      'Lower your body until chest nearly touches the floor.',
      'Push back up to starting position.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-20',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_chest_dip',
    name: 'Chest Dip',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major', 'Triceps'],
    secondaryMuscles: ['Anterior Deltoid'],
    equipment: 'bodyweight',
    instructions: [
      'Grip parallel bars and support your weight.',
      'Lean forward slightly and lower body by bending elbows.',
      'Lower until you feel a stretch in the chest.',
      'Push back up to starting position.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 90,
  },

  // ── BACK ──────────────────────────────────────────────────────────
  {
    id: 'ex_barbell_row',
    name: 'Barbell Row',
    category: 'back',
    primaryMuscles: ['Latissimus Dorsi', 'Rhomboids'],
    secondaryMuscles: ['Biceps', 'Rear Deltoid'],
    equipment: 'barbell',
    instructions: [
      'Bend at the hips with slight knee bend, back flat.',
      'Grip bar slightly wider than shoulder width.',
      'Pull bar to lower chest / upper abdomen.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 4,
    defaultReps: '6-10',
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_deadlift',
    name: 'Deadlift',
    category: 'back',
    primaryMuscles: ['Erector Spinae', 'Glutes', 'Hamstrings'],
    secondaryMuscles: ['Trapezius', 'Forearms', 'Core'],
    equipment: 'barbell',
    instructions: [
      'Stand with feet hip-width, bar over mid-foot.',
      'Hinge at hips, grip bar just outside knees.',
      'Brace core, drive through heels to stand up.',
      'Lock out hips and knees at top.',
      'Reverse the movement to lower.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '3-6',
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_pull_up',
    name: 'Pull-Up',
    category: 'back',
    primaryMuscles: ['Latissimus Dorsi'],
    secondaryMuscles: ['Biceps', 'Rhomboids', 'Forearms'],
    equipment: 'bodyweight',
    instructions: [
      'Hang from bar with overhand grip, slightly wider than shoulders.',
      'Pull yourself up until chin clears the bar.',
      'Lower with control to full hang.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '5-10',
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_lat_pulldown',
    name: 'Lat Pulldown',
    category: 'back',
    primaryMuscles: ['Latissimus Dorsi'],
    secondaryMuscles: ['Biceps', 'Rhomboids'],
    equipment: 'cable',
    instructions: [
      'Sit at lat pulldown machine, grip bar wide.',
      'Pull bar down to upper chest.',
      'Squeeze shoulder blades together.',
      'Slowly return to start.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_seated_cable_row',
    name: 'Seated Cable Row',
    category: 'back',
    primaryMuscles: ['Rhomboids', 'Latissimus Dorsi'],
    secondaryMuscles: ['Biceps', 'Rear Deltoid'],
    equipment: 'cable',
    instructions: [
      'Sit at cable row station with feet on platform.',
      'Grip handle, sit upright.',
      'Pull handle to abdomen, squeezing shoulder blades.',
      'Return with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_row',
    name: 'Dumbbell Row',
    category: 'back',
    primaryMuscles: ['Latissimus Dorsi', 'Rhomboids'],
    secondaryMuscles: ['Biceps', 'Rear Deltoid'],
    equipment: 'dumbbell',
    instructions: [
      'Place one knee and hand on bench.',
      'Hold dumbbell with opposite hand, arm hanging.',
      'Pull dumbbell to hip, elbow close to body.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_face_pull',
    name: 'Face Pull',
    category: 'back',
    primaryMuscles: ['Rear Deltoid', 'Rhomboids'],
    secondaryMuscles: ['Trapezius', 'Rotator Cuff'],
    equipment: 'cable',
    instructions: [
      'Set cable to face height with rope attachment.',
      'Pull rope toward your face, elbows high.',
      'Externally rotate at the end, pulling rope apart.',
      'Slowly return.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '15-20',
    defaultRestSeconds: 60,
  },

  // ── SHOULDERS ─────────────────────────────────────────────────────
  {
    id: 'ex_ohp',
    name: 'Overhead Press',
    category: 'shoulders',
    primaryMuscles: ['Anterior Deltoid', 'Medial Deltoid'],
    secondaryMuscles: ['Triceps', 'Upper Chest', 'Trapezius'],
    equipment: 'barbell',
    instructions: [
      'Stand with bar at shoulder height, grip just outside shoulders.',
      'Press bar overhead to full lockout.',
      'Lower with control back to shoulders.',
    ],
    isCustom: false,
    defaultSets: 4,
    defaultReps: '5-8',
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_db_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    primaryMuscles: ['Anterior Deltoid', 'Medial Deltoid'],
    secondaryMuscles: ['Triceps'],
    equipment: 'dumbbell',
    instructions: [
      'Sit or stand with dumbbells at shoulder height.',
      'Press overhead until arms are extended.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_lateral_raise',
    name: 'Lateral Raise',
    category: 'shoulders',
    primaryMuscles: ['Medial Deltoid'],
    secondaryMuscles: ['Trapezius'],
    equipment: 'dumbbell',
    instructions: [
      'Stand with dumbbells at your sides.',
      'Raise arms out to the sides until parallel with floor.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_front_raise',
    name: 'Front Raise',
    category: 'shoulders',
    primaryMuscles: ['Anterior Deltoid'],
    secondaryMuscles: ['Medial Deltoid'],
    equipment: 'dumbbell',
    instructions: [
      'Stand with dumbbells in front of thighs.',
      'Raise one or both arms forward to shoulder height.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_reverse_fly',
    name: 'Reverse Fly',
    category: 'shoulders',
    primaryMuscles: ['Rear Deltoid'],
    secondaryMuscles: ['Rhomboids', 'Trapezius'],
    equipment: 'dumbbell',
    instructions: [
      'Bend at hips with slight knee bend.',
      'Hold dumbbells below chest.',
      'Raise arms out to sides, squeezing shoulder blades.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRestSeconds: 60,
  },

  // ── LEGS ──────────────────────────────────────────────────────────
  {
    id: 'ex_squat',
    name: 'Barbell Back Squat',
    category: 'legs',
    primaryMuscles: ['Quadriceps', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Core', 'Erector Spinae'],
    equipment: 'barbell',
    instructions: [
      'Bar on upper back, feet shoulder-width apart.',
      'Brace core, push hips back and bend knees.',
      'Lower until thighs are at least parallel.',
      'Drive through heels to stand.',
    ],
    isCustom: false,
    defaultSets: 4,
    defaultReps: '5-8',
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_front_squat',
    name: 'Front Squat',
    category: 'legs',
    primaryMuscles: ['Quadriceps'],
    secondaryMuscles: ['Glutes', 'Core'],
    equipment: 'barbell',
    instructions: [
      'Bar on front of shoulders in clean grip or cross-arm grip.',
      'Keep elbows high, chest up.',
      'Squat down keeping torso upright.',
      'Drive back up.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '6-10',
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_leg_press',
    name: 'Leg Press',
    category: 'legs',
    primaryMuscles: ['Quadriceps', 'Glutes'],
    secondaryMuscles: ['Hamstrings'],
    equipment: 'machine',
    instructions: [
      'Sit in leg press machine, feet shoulder-width on platform.',
      'Release safeties and lower platform by bending knees.',
      'Press platform back up without locking knees.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_romanian_deadlift',
    name: 'Romanian Deadlift',
    category: 'legs',
    primaryMuscles: ['Hamstrings', 'Glutes'],
    secondaryMuscles: ['Erector Spinae'],
    equipment: 'barbell',
    instructions: [
      'Stand with bar at hip height, slight knee bend.',
      'Hinge at hips, pushing them back.',
      'Lower bar along legs until you feel a hamstring stretch.',
      'Drive hips forward to return.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_leg_curl',
    name: 'Leg Curl',
    category: 'legs',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: [],
    equipment: 'machine',
    instructions: [
      'Lie face down on leg curl machine.',
      'Hook heels under pad.',
      'Curl weight up by bending knees.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-15',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_leg_extension',
    name: 'Leg Extension',
    category: 'legs',
    primaryMuscles: ['Quadriceps'],
    secondaryMuscles: [],
    equipment: 'machine',
    instructions: [
      'Sit on leg extension machine, shins against pad.',
      'Extend legs until knees are straight.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-15',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_lunge',
    name: 'Walking Lunge',
    category: 'legs',
    primaryMuscles: ['Quadriceps', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Core'],
    equipment: 'dumbbell',
    instructions: [
      'Hold dumbbells at sides.',
      'Step forward into a lunge, both knees at 90 degrees.',
      'Push off front foot and step forward with back foot.',
      'Continue alternating.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_calf_raise',
    name: 'Standing Calf Raise',
    category: 'legs',
    primaryMuscles: ['Gastrocnemius', 'Soleus'],
    secondaryMuscles: [],
    equipment: 'machine',
    instructions: [
      'Stand on calf raise machine with balls of feet on platform.',
      'Rise up onto toes as high as possible.',
      'Lower with control until you feel a stretch.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '12-20',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    category: 'legs',
    primaryMuscles: ['Quadriceps', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Core'],
    equipment: 'dumbbell',
    instructions: [
      'Stand with one foot elevated behind you on a bench.',
      'Hold dumbbells at sides.',
      'Lower into a lunge until back knee nearly touches floor.',
      'Drive through front foot to stand.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 90,
  },

  // ── ARMS ──────────────────────────────────────────────────────────
  {
    id: 'ex_barbell_curl',
    name: 'Barbell Curl',
    category: 'arms',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis', 'Forearms'],
    equipment: 'barbell',
    instructions: [
      'Stand with bar at arm\'s length, underhand grip.',
      'Curl bar up to shoulder height, keeping elbows stationary.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_db_curl',
    name: 'Dumbbell Curl',
    category: 'arms',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    equipment: 'dumbbell',
    instructions: [
      'Stand with dumbbells at sides, palms forward.',
      'Curl both or alternating dumbbells to shoulders.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_hammer_curl',
    name: 'Hammer Curl',
    category: 'arms',
    primaryMuscles: ['Brachialis', 'Biceps'],
    secondaryMuscles: ['Forearms'],
    equipment: 'dumbbell',
    instructions: [
      'Stand with dumbbells at sides, palms facing in (neutral grip).',
      'Curl dumbbells up keeping palms facing in.',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_tricep_pushdown',
    name: 'Tricep Pushdown',
    category: 'arms',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    equipment: 'cable',
    instructions: [
      'Stand at cable station with bar or rope attachment at high position.',
      'Push down until arms are fully extended.',
      'Keep elbows close to body.',
      'Return with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-15',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_skull_crusher',
    name: 'Skull Crusher',
    category: 'arms',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    equipment: 'barbell',
    instructions: [
      'Lie on bench with EZ bar or barbell at arm\'s length above chest.',
      'Bend elbows to lower bar toward forehead.',
      'Extend elbows to press back up.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_overhead_tricep_ext',
    name: 'Overhead Tricep Extension',
    category: 'arms',
    primaryMuscles: ['Triceps (Long Head)'],
    secondaryMuscles: [],
    equipment: 'dumbbell',
    instructions: [
      'Hold dumbbell overhead with both hands.',
      'Lower behind head by bending elbows.',
      'Extend arms back overhead.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSeconds: 60,
  },

  // ── CORE ──────────────────────────────────────────────────────────
  {
    id: 'ex_plank',
    name: 'Plank',
    category: 'core',
    primaryMuscles: ['Rectus Abdominis', 'Transverse Abdominis'],
    secondaryMuscles: ['Obliques', 'Erector Spinae'],
    equipment: 'bodyweight',
    instructions: [
      'Start face down, then lift body on forearms and toes.',
      'Keep body in a straight line from head to heels.',
      'Brace core and hold.',
    ],
    isCustom: false,
    isTimeBased: true,
    defaultDurationSeconds: 60,
    defaultSets: 3,
    defaultReps: '30-60s',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_wall_sit',
    name: 'Wall Sit',
    category: 'legs',
    primaryMuscles: ['Quadriceps'],
    secondaryMuscles: ['Glutes', 'Calves'],
    equipment: 'bodyweight',
    instructions: [
      'Stand with back flat against a wall.',
      'Slide down until thighs are parallel to the floor.',
      'Hold the position for the target duration.',
    ],
    isCustom: false,
    isTimeBased: true,
    defaultDurationSeconds: 60,
    defaultSets: 3,
    defaultReps: '30-60s',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_dead_hang',
    name: 'Dead Hang',
    category: 'back',
    primaryMuscles: ['Forearms', 'Latissimus Dorsi'],
    secondaryMuscles: ['Shoulders', 'Core'],
    equipment: 'bodyweight',
    instructions: [
      'Grip a pull-up bar with an overhand grip.',
      'Hang with arms fully extended and shoulders engaged.',
      'Hold for the target duration.',
    ],
    isCustom: false,
    isTimeBased: true,
    defaultDurationSeconds: 45,
    defaultSets: 3,
    defaultReps: '30-45s',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_hanging_leg_raise',
    name: 'Hanging Leg Raise',
    category: 'core',
    primaryMuscles: ['Rectus Abdominis', 'Hip Flexors'],
    secondaryMuscles: ['Obliques'],
    equipment: 'bodyweight',
    instructions: [
      'Hang from pull-up bar.',
      'Raise legs until they are parallel to the floor (or higher).',
      'Lower with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-15',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_crunch',
    name: 'Cable Crunch',
    category: 'core',
    primaryMuscles: ['Rectus Abdominis'],
    secondaryMuscles: ['Obliques'],
    equipment: 'cable',
    instructions: [
      'Kneel in front of cable machine with rope at high position.',
      'Hold rope behind head.',
      'Crunch down by flexing your spine.',
      'Return with control.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_russian_twist',
    name: 'Russian Twist',
    category: 'core',
    primaryMuscles: ['Obliques'],
    secondaryMuscles: ['Rectus Abdominis'],
    equipment: 'bodyweight',
    instructions: [
      'Sit with knees bent, feet off floor, leaning back slightly.',
      'Rotate torso side to side.',
      'Optional: hold a weight plate or dumbbell.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '15-20',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_ab_wheel',
    name: 'Ab Wheel Rollout',
    category: 'core',
    primaryMuscles: ['Rectus Abdominis', 'Transverse Abdominis'],
    secondaryMuscles: ['Erector Spinae', 'Latissimus Dorsi'],
    equipment: 'bodyweight',
    instructions: [
      'Kneel with ab wheel in front of you.',
      'Roll forward extending body as far as you can control.',
      'Use core to pull back to starting position.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 60,
  },

  // ── CARDIO ────────────────────────────────────────────────────────
  {
    id: 'ex_treadmill_run',
    name: 'Treadmill Run',
    category: 'cardio',
    primaryMuscles: ['Quadriceps', 'Hamstrings', 'Calves'],
    secondaryMuscles: ['Glutes', 'Core'],
    equipment: 'machine',
    instructions: [
      'Set treadmill to desired speed and incline.',
      'Run at a steady pace for target duration.',
    ],
    isCustom: false,
    defaultSets: 1,
    defaultReps: '20-30min',
    defaultRestSeconds: 0,
  },
  {
    id: 'ex_rowing_machine',
    name: 'Rowing Machine',
    category: 'cardio',
    primaryMuscles: ['Back', 'Legs'],
    secondaryMuscles: ['Arms', 'Core'],
    equipment: 'machine',
    instructions: [
      'Sit on rower, strap feet in.',
      'Push with legs first, then pull with arms.',
      'Reverse the motion to return.',
    ],
    isCustom: false,
    defaultSets: 1,
    defaultReps: '15-20min',
    defaultRestSeconds: 0,
  },

  // ── FULL BODY ─────────────────────────────────────────────────────
  {
    id: 'ex_clean_and_press',
    name: 'Clean and Press',
    category: 'full_body',
    primaryMuscles: ['Shoulders', 'Trapezius', 'Legs'],
    secondaryMuscles: ['Glutes', 'Core', 'Triceps'],
    equipment: 'barbell',
    instructions: [
      'Start with bar on the floor.',
      'Clean the bar to shoulders with an explosive pull.',
      'Press overhead to full lockout.',
      'Lower back to shoulders, then to floor.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '5-8',
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_kettlebell_swing',
    name: 'Kettlebell Swing',
    category: 'full_body',
    primaryMuscles: ['Glutes', 'Hamstrings'],
    secondaryMuscles: ['Core', 'Shoulders', 'Back'],
    equipment: 'kettlebell',
    instructions: [
      'Stand with feet wider than shoulders, kettlebell in front.',
      'Hinge at hips and swing kettlebell back between legs.',
      'Drive hips forward explosively to swing kettlebell to chest height.',
      'Let it swing back and repeat.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '15-20',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_burpee',
    name: 'Burpee',
    category: 'full_body',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Core', 'Chest', 'Legs'],
    equipment: 'bodyweight',
    instructions: [
      'From standing, drop into a squat with hands on floor.',
      'Kick feet back into push-up position.',
      'Do a push-up.',
      'Jump feet back to squat.',
      'Jump up explosively.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-15',
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_thruster',
    name: 'Dumbbell Thruster',
    category: 'full_body',
    primaryMuscles: ['Quadriceps', 'Shoulders'],
    secondaryMuscles: ['Glutes', 'Triceps', 'Core'],
    equipment: 'dumbbell',
    instructions: [
      'Hold dumbbells at shoulder height.',
      'Squat down to parallel.',
      'Drive up explosively and press dumbbells overhead.',
      'Lower dumbbells back to shoulders.',
    ],
    isCustom: false,
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSeconds: 90,
  },
];

// ── Seed Programs ───────────────────────────────────────────────────

export function getSeedPrograms(userId: string) {
  const now = new Date().toISOString();
  return [
    {
      id: 'prog_ppl',
      userId,
      name: 'Push Pull Legs',
      description: 'Classic 6-day PPL split for intermediate to advanced lifters. Each muscle group is hit twice per week.',
      daysPerWeek: 6,
      difficulty: 'intermediate' as const,
      days: [
        {
          id: 'ppl_day1',
          programId: 'prog_ppl',
          dayNumber: 1,
          name: 'Push A',
          focusArea: 'chest' as const,
          exercises: [
            { id: 'pe_1', exerciseId: 'ex_bench_press', exerciseName: 'Barbell Bench Press', targetSets: 4, targetReps: '6-8', restSeconds: 120, order: 1 },
            { id: 'pe_2', exerciseId: 'ex_ohp', exerciseName: 'Overhead Press', targetSets: 3, targetReps: '8-10', restSeconds: 90, order: 2 },
            { id: 'pe_3', exerciseId: 'ex_incline_bench', exerciseName: 'Incline Barbell Bench Press', targetSets: 3, targetReps: '8-12', restSeconds: 90, order: 3 },
            { id: 'pe_4', exerciseId: 'ex_lateral_raise', exerciseName: 'Lateral Raise', targetSets: 3, targetReps: '12-15', restSeconds: 60, order: 4 },
            { id: 'pe_5', exerciseId: 'ex_tricep_pushdown', exerciseName: 'Tricep Pushdown', targetSets: 3, targetReps: '10-15', restSeconds: 60, order: 5 },
            { id: 'pe_6', exerciseId: 'ex_overhead_tricep_ext', exerciseName: 'Overhead Tricep Extension', targetSets: 3, targetReps: '10-12', restSeconds: 60, order: 6 },
          ],
        },
        {
          id: 'ppl_day2',
          programId: 'prog_ppl',
          dayNumber: 2,
          name: 'Pull A',
          focusArea: 'back' as const,
          exercises: [
            { id: 'pe_7', exerciseId: 'ex_deadlift', exerciseName: 'Deadlift', targetSets: 3, targetReps: '3-5', restSeconds: 180, order: 1 },
            { id: 'pe_8', exerciseId: 'ex_pull_up', exerciseName: 'Pull-Up', targetSets: 3, targetReps: '6-10', restSeconds: 120, order: 2 },
            { id: 'pe_9', exerciseId: 'ex_barbell_row', exerciseName: 'Barbell Row', targetSets: 3, targetReps: '8-10', restSeconds: 90, order: 3 },
            { id: 'pe_10', exerciseId: 'ex_face_pull', exerciseName: 'Face Pull', targetSets: 3, targetReps: '15-20', restSeconds: 60, order: 4 },
            { id: 'pe_11', exerciseId: 'ex_barbell_curl', exerciseName: 'Barbell Curl', targetSets: 3, targetReps: '8-12', restSeconds: 60, order: 5 },
            { id: 'pe_12', exerciseId: 'ex_hammer_curl', exerciseName: 'Hammer Curl', targetSets: 3, targetReps: '10-12', restSeconds: 60, order: 6 },
          ],
        },
        {
          id: 'ppl_day3',
          programId: 'prog_ppl',
          dayNumber: 3,
          name: 'Legs A',
          focusArea: 'legs' as const,
          exercises: [
            { id: 'pe_13', exerciseId: 'ex_squat', exerciseName: 'Barbell Back Squat', targetSets: 4, targetReps: '5-8', restSeconds: 180, order: 1 },
            { id: 'pe_14', exerciseId: 'ex_romanian_deadlift', exerciseName: 'Romanian Deadlift', targetSets: 3, targetReps: '8-12', restSeconds: 120, order: 2 },
            { id: 'pe_15', exerciseId: 'ex_leg_press', exerciseName: 'Leg Press', targetSets: 3, targetReps: '10-12', restSeconds: 120, order: 3 },
            { id: 'pe_16', exerciseId: 'ex_leg_curl', exerciseName: 'Leg Curl', targetSets: 3, targetReps: '10-15', restSeconds: 60, order: 4 },
            { id: 'pe_17', exerciseId: 'ex_calf_raise', exerciseName: 'Standing Calf Raise', targetSets: 4, targetReps: '12-20', restSeconds: 60, order: 5 },
          ],
        },
        {
          id: 'ppl_day4',
          programId: 'prog_ppl',
          dayNumber: 4,
          name: 'Push B',
          focusArea: 'chest' as const,
          exercises: [
            { id: 'pe_18', exerciseId: 'ex_db_bench_press', exerciseName: 'Dumbbell Bench Press', targetSets: 4, targetReps: '8-12', restSeconds: 90, order: 1 },
            { id: 'pe_19', exerciseId: 'ex_db_shoulder_press', exerciseName: 'Dumbbell Shoulder Press', targetSets: 3, targetReps: '8-12', restSeconds: 90, order: 2 },
            { id: 'pe_20', exerciseId: 'ex_cable_crossover', exerciseName: 'Cable Crossover', targetSets: 3, targetReps: '12-15', restSeconds: 60, order: 3 },
            { id: 'pe_21', exerciseId: 'ex_lateral_raise', exerciseName: 'Lateral Raise', targetSets: 4, targetReps: '12-15', restSeconds: 60, order: 4 },
            { id: 'pe_22', exerciseId: 'ex_skull_crusher', exerciseName: 'Skull Crusher', targetSets: 3, targetReps: '8-12', restSeconds: 60, order: 5 },
          ],
        },
        {
          id: 'ppl_day5',
          programId: 'prog_ppl',
          dayNumber: 5,
          name: 'Pull B',
          focusArea: 'back' as const,
          exercises: [
            { id: 'pe_23', exerciseId: 'ex_barbell_row', exerciseName: 'Barbell Row', targetSets: 4, targetReps: '6-8', restSeconds: 120, order: 1 },
            { id: 'pe_24', exerciseId: 'ex_lat_pulldown', exerciseName: 'Lat Pulldown', targetSets: 3, targetReps: '8-12', restSeconds: 90, order: 2 },
            { id: 'pe_25', exerciseId: 'ex_seated_cable_row', exerciseName: 'Seated Cable Row', targetSets: 3, targetReps: '10-12', restSeconds: 90, order: 3 },
            { id: 'pe_26', exerciseId: 'ex_face_pull', exerciseName: 'Face Pull', targetSets: 3, targetReps: '15-20', restSeconds: 60, order: 4 },
            { id: 'pe_27', exerciseId: 'ex_db_curl', exerciseName: 'Dumbbell Curl', targetSets: 3, targetReps: '10-12', restSeconds: 60, order: 5 },
          ],
        },
        {
          id: 'ppl_day6',
          programId: 'prog_ppl',
          dayNumber: 6,
          name: 'Legs B',
          focusArea: 'legs' as const,
          exercises: [
            { id: 'pe_28', exerciseId: 'ex_front_squat', exerciseName: 'Front Squat', targetSets: 3, targetReps: '6-10', restSeconds: 120, order: 1 },
            { id: 'pe_29', exerciseId: 'ex_bulgarian_split_squat', exerciseName: 'Bulgarian Split Squat', targetSets: 3, targetReps: '8-12', restSeconds: 90, order: 2 },
            { id: 'pe_30', exerciseId: 'ex_leg_extension', exerciseName: 'Leg Extension', targetSets: 3, targetReps: '10-15', restSeconds: 60, order: 3 },
            { id: 'pe_31', exerciseId: 'ex_leg_curl', exerciseName: 'Leg Curl', targetSets: 3, targetReps: '10-15', restSeconds: 60, order: 4 },
            { id: 'pe_32', exerciseId: 'ex_calf_raise', exerciseName: 'Standing Calf Raise', targetSets: 4, targetReps: '12-20', restSeconds: 60, order: 5 },
            { id: 'pe_33', exerciseId: 'ex_hanging_leg_raise', exerciseName: 'Hanging Leg Raise', targetSets: 3, targetReps: '10-15', restSeconds: 60, order: 6 },
          ],
        },
      ],
      isActive: true,
      createdBy: 'ai' as const,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'prog_upper_lower',
      userId,
      name: 'Upper / Lower Split',
      description: 'Classic 4-day upper/lower split. Great for intermediates seeking balanced strength and hypertrophy.',
      daysPerWeek: 4,
      difficulty: 'intermediate' as const,
      days: [
        {
          id: 'ul_day1',
          programId: 'prog_upper_lower',
          dayNumber: 1,
          name: 'Upper A (Strength)',
          focusArea: 'chest' as const,
          exercises: [
            { id: 'pe_34', exerciseId: 'ex_bench_press', exerciseName: 'Barbell Bench Press', targetSets: 4, targetReps: '4-6', restSeconds: 180, order: 1 },
            { id: 'pe_35', exerciseId: 'ex_barbell_row', exerciseName: 'Barbell Row', targetSets: 4, targetReps: '4-6', restSeconds: 180, order: 2 },
            { id: 'pe_36', exerciseId: 'ex_ohp', exerciseName: 'Overhead Press', targetSets: 3, targetReps: '6-8', restSeconds: 120, order: 3 },
            { id: 'pe_37', exerciseId: 'ex_pull_up', exerciseName: 'Pull-Up', targetSets: 3, targetReps: '6-10', restSeconds: 120, order: 4 },
            { id: 'pe_38', exerciseId: 'ex_barbell_curl', exerciseName: 'Barbell Curl', targetSets: 2, targetReps: '8-12', restSeconds: 60, order: 5 },
            { id: 'pe_39', exerciseId: 'ex_skull_crusher', exerciseName: 'Skull Crusher', targetSets: 2, targetReps: '8-12', restSeconds: 60, order: 6 },
          ],
        },
        {
          id: 'ul_day2',
          programId: 'prog_upper_lower',
          dayNumber: 2,
          name: 'Lower A (Strength)',
          focusArea: 'legs' as const,
          exercises: [
            { id: 'pe_40', exerciseId: 'ex_squat', exerciseName: 'Barbell Back Squat', targetSets: 4, targetReps: '4-6', restSeconds: 180, order: 1 },
            { id: 'pe_41', exerciseId: 'ex_romanian_deadlift', exerciseName: 'Romanian Deadlift', targetSets: 3, targetReps: '6-8', restSeconds: 120, order: 2 },
            { id: 'pe_42', exerciseId: 'ex_leg_press', exerciseName: 'Leg Press', targetSets: 3, targetReps: '8-10', restSeconds: 120, order: 3 },
            { id: 'pe_43', exerciseId: 'ex_leg_curl', exerciseName: 'Leg Curl', targetSets: 3, targetReps: '10-12', restSeconds: 60, order: 4 },
            { id: 'pe_44', exerciseId: 'ex_calf_raise', exerciseName: 'Standing Calf Raise', targetSets: 4, targetReps: '10-15', restSeconds: 60, order: 5 },
          ],
        },
        {
          id: 'ul_day3',
          programId: 'prog_upper_lower',
          dayNumber: 3,
          name: 'Upper B (Hypertrophy)',
          focusArea: 'back' as const,
          exercises: [
            { id: 'pe_45', exerciseId: 'ex_db_bench_press', exerciseName: 'Dumbbell Bench Press', targetSets: 3, targetReps: '8-12', restSeconds: 90, order: 1 },
            { id: 'pe_46', exerciseId: 'ex_lat_pulldown', exerciseName: 'Lat Pulldown', targetSets: 3, targetReps: '8-12', restSeconds: 90, order: 2 },
            { id: 'pe_47', exerciseId: 'ex_db_shoulder_press', exerciseName: 'Dumbbell Shoulder Press', targetSets: 3, targetReps: '10-12', restSeconds: 90, order: 3 },
            { id: 'pe_48', exerciseId: 'ex_seated_cable_row', exerciseName: 'Seated Cable Row', targetSets: 3, targetReps: '10-12', restSeconds: 90, order: 4 },
            { id: 'pe_49', exerciseId: 'ex_lateral_raise', exerciseName: 'Lateral Raise', targetSets: 3, targetReps: '12-15', restSeconds: 60, order: 5 },
            { id: 'pe_50', exerciseId: 'ex_db_curl', exerciseName: 'Dumbbell Curl', targetSets: 2, targetReps: '10-15', restSeconds: 60, order: 6 },
          ],
        },
        {
          id: 'ul_day4',
          programId: 'prog_upper_lower',
          dayNumber: 4,
          name: 'Lower B (Hypertrophy)',
          focusArea: 'legs' as const,
          exercises: [
            { id: 'pe_51', exerciseId: 'ex_front_squat', exerciseName: 'Front Squat', targetSets: 3, targetReps: '8-10', restSeconds: 120, order: 1 },
            { id: 'pe_52', exerciseId: 'ex_bulgarian_split_squat', exerciseName: 'Bulgarian Split Squat', targetSets: 3, targetReps: '10-12', restSeconds: 90, order: 2 },
            { id: 'pe_53', exerciseId: 'ex_leg_extension', exerciseName: 'Leg Extension', targetSets: 3, targetReps: '12-15', restSeconds: 60, order: 3 },
            { id: 'pe_54', exerciseId: 'ex_leg_curl', exerciseName: 'Leg Curl', targetSets: 3, targetReps: '12-15', restSeconds: 60, order: 4 },
            { id: 'pe_55', exerciseId: 'ex_calf_raise', exerciseName: 'Standing Calf Raise', targetSets: 4, targetReps: '15-20', restSeconds: 60, order: 5 },
          ],
        },
      ],
      isActive: false,
      createdBy: 'ai' as const,
      createdAt: now,
      updatedAt: now,
    },
  ];
}
