// ── Seed Recipe Data ─────────────────────────────────────────────────
// 100 production-ready healthy recipes imported from the curated CSV.
// Each recipe is pre-tagged with source: 'seed' so it coexists cleanly
// with user-created and AI-generated recipes.

import type { RecipeEntry, RecipeDifficulty } from '../types/nutrition';

// ── Raw CSV row shape ───────────────────────────────────────────────

interface RawRecipeRow {
  id: number;
  name: string;
  difficulty: RecipeDifficulty;
  equipment: string;       // semicolon-separated
  ingredients: string;     // comma-separated
  instructions: string;    // numbered steps
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  fiber_g: number;
  calories: number;
}

// ── CSV data (100 rows) ─────────────────────────────────────────────

const RAW_RECIPES: RawRecipeRow[] = [
  { id: 1, name: 'Quinoa Veggie Bowl', difficulty: 'Easy', equipment: 'stove', ingredients: '1 cup quinoa, 1 cup mixed bell peppers (diced), 1 cup zucchini (diced), 1/2 cup black beans, 1/2 avocado, 2 tbsp olive oil, 1 lime (juiced), salt, pepper, cumin', instructions: '1. Cook quinoa according to package directions. 2. Heat olive oil in a pan over medium heat. 3. Sauté bell peppers and zucchini for 5-6 minutes until tender. 4. Drain and rinse black beans. 5. Assemble bowl with quinoa base, top with sautéed veggies and black beans. 6. Slice avocado and place on top. 7. Squeeze lime juice over everything and season with cumin, salt, and pepper.', protein_g: 42, carbs_g: 50, fat_g: 15, fiber_g: 7, calories: 503 },
  { id: 2, name: 'Chicken Pasta', difficulty: 'Easy', equipment: 'oven', ingredients: '8 oz whole wheat penne, 6 oz chicken breast, 1 cup cherry tomatoes (halved), 2 cups spinach, 3 cloves garlic (minced), 2 tbsp olive oil, 1/4 cup parmesan cheese, Italian seasoning, salt, pepper', instructions: '1. Cook penne according to package directions, reserve 1/2 cup pasta water. 2. Season chicken breast with Italian seasoning, salt, and pepper. 3. Heat 1 tbsp olive oil in a skillet and cook chicken 6-7 minutes per side until done, then slice. 4. In the same pan, add remaining olive oil and sauté garlic for 30 seconds. 5. Add cherry tomatoes and cook 2-3 minutes. 6. Add spinach and stir until wilted. 7. Toss in cooked pasta with a splash of pasta water. 8. Top with sliced chicken and parmesan.', protein_g: 47, carbs_g: 42, fat_g: 14, fiber_g: 9, calories: 482 },
  { id: 3, name: 'Grilled Chicken Quinoa Bowl', difficulty: 'Easy', equipment: 'stove;pot', ingredients: '6 oz chicken breast, 1 cup quinoa, 1 cup cucumber (diced), 1/2 cup cherry tomatoes (halved), 1/4 cup red onion (diced), 2 tbsp lemon juice, 1 tbsp olive oil, fresh parsley, salt, pepper', instructions: '1. Cook quinoa according to package directions and let cool slightly. 2. Season chicken breast with salt, pepper, and olive oil. 3. Grill chicken on medium-high heat for 6-7 minutes per side until internal temp reaches 165°F. 4. Let chicken rest 5 minutes, then slice. 5. Toss quinoa with cucumber, tomatoes, red onion, lemon juice, and parsley. 6. Arrange quinoa mixture in a bowl and top with sliced grilled chicken.', protein_g: 27, carbs_g: 56, fat_g: 7, fiber_g: 10, calories: 395 },
  { id: 4, name: 'Chicken Caesar Salad', difficulty: 'Easy', equipment: 'none', ingredients: '6 oz chicken breast, 4 cups romaine lettuce (chopped), 1/4 cup parmesan cheese (shaved), 1/2 cup whole wheat croutons, 2 tbsp Caesar dressing, 1 lemon (juiced), 1 tsp olive oil, salt, pepper', instructions: '1. Season chicken breast with salt, pepper, and olive oil. 2. Grill or pan-sear chicken for 6-7 minutes per side until cooked through. 3. Let chicken rest 5 minutes, then slice. 4. Chop romaine lettuce and place in a large bowl. 5. Add croutons and shaved parmesan. 6. Toss with Caesar dressing and lemon juice. 7. Top with sliced chicken and serve.', protein_g: 42, carbs_g: 49, fat_g: 10, fiber_g: 6, calories: 454 },
  { id: 5, name: 'Beef Burrito Bowl', difficulty: 'Easy', equipment: 'stove;pan', ingredients: '6 oz lean ground beef, 1 cup brown rice, 1/2 cup black beans, 1/2 cup corn kernels, 1/4 cup salsa, 1/4 avocado, 2 tbsp sour cream, 1 tsp cumin, 1 tsp chili powder, salt, pepper, lime wedge', instructions: '1. Cook brown rice according to package directions. 2. Season ground beef with cumin, chili powder, salt, and pepper. 3. Cook beef in a skillet over medium-high heat, breaking it up, for 6-8 minutes until browned. 4. Warm black beans and corn in a small saucepan. 5. Build the bowl: rice on the bottom, top with seasoned beef, beans, and corn. 6. Add salsa, sliced avocado, and a dollop of sour cream. 7. Squeeze lime wedge over the top.', protein_g: 22, carbs_g: 54, fat_g: 20, fiber_g: 5, calories: 484 },
  { id: 6, name: 'Egg White Omelette', difficulty: 'Easy', equipment: 'stove;pot', ingredients: '6 egg whites, 1/4 cup bell peppers (diced), 1/4 cup mushrooms (sliced), 1/4 cup spinach, 2 tbsp feta cheese, 1 tsp olive oil, salt, pepper, dried herbs', instructions: '1. Whisk egg whites with a pinch of salt and pepper until slightly frothy. 2. Heat olive oil in a non-stick skillet over medium heat. 3. Add bell peppers and mushrooms, sauté 3-4 minutes until softened. 4. Add spinach and stir until wilted, about 1 minute. 5. Pour egg whites evenly over the vegetables. 6. Cook undisturbed 2-3 minutes until edges set. 7. Sprinkle feta cheese on one half, fold omelette over. 8. Cook 1-2 more minutes until set, then serve.', protein_g: 24, carbs_g: 32, fat_g: 11, fiber_g: 12, calories: 323 },
  { id: 7, name: 'Tofu Veggie Stir Fry', difficulty: 'Easy', equipment: 'oven', ingredients: '14 oz extra-firm tofu (pressed and cubed), 1 cup broccoli florets, 1 red bell pepper (sliced), 1 cup snap peas, 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tbsp soy sauce, 1 tbsp sesame oil, 1 tbsp cornstarch, 1 cup brown rice', instructions: '1. Press tofu for 15 minutes, then cut into cubes and toss with cornstarch. 2. Cook brown rice according to package directions. 3. Heat sesame oil in a wok or large skillet over high heat. 4. Add tofu cubes and cook 5-6 minutes, turning until golden on all sides. Remove and set aside. 5. Add broccoli, bell pepper, and snap peas to the wok. Stir-fry 4-5 minutes. 6. Add garlic and ginger, cook 30 seconds. 7. Return tofu to wok, add soy sauce, and toss everything together. 8. Serve over brown rice.', protein_g: 47, carbs_g: 35, fat_g: 13, fiber_g: 7, calories: 445 },
  { id: 8, name: 'Lentil Curry', difficulty: 'Easy', equipment: 'none', ingredients: '1 cup red lentils, 1 can coconut milk (light), 1 can diced tomatoes, 1 onion (diced), 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tsp curry powder, 1 tsp turmeric, 1 tsp cumin, 1 tbsp olive oil, fresh cilantro, salt', instructions: '1. Rinse lentils under cold water. 2. Heat olive oil in a large pot over medium heat. 3. Sauté diced onion for 5 minutes until softened. 4. Add garlic, ginger, curry powder, turmeric, and cumin. Stir for 1 minute until fragrant. 5. Add lentils, diced tomatoes, and coconut milk. Stir to combine. 6. Bring to a boil, then reduce heat and simmer 20-25 minutes until lentils are tender. 7. Season with salt to taste. 8. Serve garnished with fresh cilantro.', protein_g: 26, carbs_g: 35, fat_g: 17, fiber_g: 8, calories: 397 },
  { id: 9, name: 'Avocado Toast with Eggs', difficulty: 'Easy', equipment: 'stove', ingredients: '2 slices whole grain bread, 1 ripe avocado, 2 large eggs, 1 tsp lemon juice, red pepper flakes, salt, pepper, everything bagel seasoning (optional)', instructions: '1. Toast bread slices until golden and crispy. 2. While bread toasts, cook eggs to your preference (fried, poached, or scrambled). 3. Halve the avocado, remove pit, and scoop flesh into a bowl. 4. Mash avocado with lemon juice, salt, and pepper. 5. Spread mashed avocado evenly on both toast slices. 6. Top each toast with a cooked egg. 7. Sprinkle with red pepper flakes and everything bagel seasoning if desired.', protein_g: 24, carbs_g: 41, fat_g: 11, fiber_g: 7, calories: 359 },
  { id: 10, name: 'Greek Yogurt Parfait', difficulty: 'Easy', equipment: 'oven;sheet pan', ingredients: '1 cup plain Greek yogurt, 1/3 cup granola, 1/2 cup mixed berries (blueberries, strawberries, raspberries), 1 tbsp honey, 1 tbsp chia seeds, 1 tbsp almond butter', instructions: '1. Spoon half the Greek yogurt into a glass or bowl. 2. Add a layer of half the mixed berries. 3. Sprinkle half the granola over the berries. 4. Repeat layers with remaining yogurt, berries, and granola. 5. Drizzle honey over the top. 6. Add chia seeds and a dollop of almond butter. 7. Serve immediately or refrigerate up to 4 hours.', protein_g: 24, carbs_g: 28, fat_g: 19, fiber_g: 11, calories: 379 },
  { id: 11, name: 'Protein Smoothie', difficulty: 'Easy', equipment: 'oven;sheet pan', ingredients: '1 scoop whey protein powder (vanilla or chocolate), 1 banana, 1 cup unsweetened almond milk, 1 tbsp peanut butter, 1/2 cup frozen berries, 1 handful spinach, 1/2 cup ice', instructions: '1. Add almond milk and spinach to blender, blend until smooth. 2. Add banana, frozen berries, and peanut butter. 3. Add protein powder and ice. 4. Blend on high for 60-90 seconds until creamy and smooth. 5. Pour into a glass and serve immediately.', protein_g: 38, carbs_g: 60, fat_g: 15, fiber_g: 4, calories: 527 },
  { id: 12, name: 'Chicken Pasta', difficulty: 'Easy', equipment: 'oven;sheet pan', ingredients: '8 oz whole wheat penne, 6 oz chicken breast, 1 cup cherry tomatoes (halved), 2 cups spinach, 3 cloves garlic (minced), 2 tbsp olive oil, 1/4 cup parmesan cheese, Italian seasoning, salt, pepper', instructions: '1. Cook penne according to package directions, reserve 1/2 cup pasta water. 2. Season chicken breast with Italian seasoning, salt, and pepper. 3. Heat 1 tbsp olive oil in a skillet and cook chicken 6-7 minutes per side until done, then slice. 4. In the same pan, add remaining olive oil and sauté garlic for 30 seconds. 5. Add cherry tomatoes and cook 2-3 minutes. 6. Add spinach and stir until wilted. 7. Toss in cooked pasta with a splash of pasta water. 8. Top with sliced chicken and parmesan.', protein_g: 44, carbs_g: 28, fat_g: 5, fiber_g: 5, calories: 333 },
  { id: 13, name: 'Beef Burrito Bowl', difficulty: 'Easy', equipment: 'stove;pan', ingredients: '6 oz lean ground beef, 1 cup brown rice, 1/2 cup black beans, 1/2 cup corn kernels, 1/4 cup salsa, 1/4 avocado, 2 tbsp sour cream, 1 tsp cumin, 1 tsp chili powder, salt, pepper, lime wedge', instructions: '1. Cook brown rice according to package directions. 2. Season ground beef with cumin, chili powder, salt, and pepper. 3. Cook beef in a skillet over medium-high heat, breaking it up, for 6-8 minutes until browned. 4. Warm black beans and corn in a small saucepan. 5. Build the bowl: rice on the bottom, top with seasoned beef, beans, and corn. 6. Add salsa, sliced avocado, and a dollop of sour cream. 7. Squeeze lime wedge over the top.', protein_g: 29, carbs_g: 41, fat_g: 9, fiber_g: 8, calories: 361 },
  { id: 14, name: 'Avocado Toast with Eggs', difficulty: 'Easy', equipment: 'oven', ingredients: '2 slices whole grain bread, 1 ripe avocado, 2 large eggs, 1 tsp lemon juice, red pepper flakes, salt, pepper, everything bagel seasoning (optional)', instructions: '1. Toast bread slices until golden and crispy. 2. While bread toasts, cook eggs to your preference (fried, poached, or scrambled). 3. Halve the avocado, remove pit, and scoop flesh into a bowl. 4. Mash avocado with lemon juice, salt, and pepper. 5. Spread mashed avocado evenly on both toast slices. 6. Top each toast with a cooked egg. 7. Sprinkle with red pepper flakes and everything bagel seasoning if desired.', protein_g: 36, carbs_g: 29, fat_g: 16, fiber_g: 9, calories: 404 },
  { id: 15, name: 'Salmon Avocado Rice Bowl', difficulty: 'Easy', equipment: 'blender', ingredients: '6 oz salmon fillet, 1 cup sushi rice, 1/2 avocado (sliced), 1/2 cucumber (sliced), 1 tbsp soy sauce, 1 tsp rice vinegar, 1 tsp sesame seeds, 1 sheet nori (crumbled), pickled ginger (optional), sriracha mayo', instructions: '1. Cook sushi rice according to package directions, season with rice vinegar. 2. Season salmon with salt and pepper. 3. Pan-sear salmon skin-side down in a hot skillet for 4 minutes, flip and cook 3 more minutes. 4. Flake salmon into large chunks. 5. Assemble bowl with rice base, top with salmon, sliced avocado, and cucumber. 6. Drizzle soy sauce and sriracha mayo. 7. Garnish with sesame seeds and crumbled nori.', protein_g: 28, carbs_g: 56, fat_g: 8, fiber_g: 11, calories: 408 },
  { id: 16, name: 'Egg White Omelette', difficulty: 'Easy', equipment: 'oven', ingredients: '6 egg whites, 1/4 cup bell peppers (diced), 1/4 cup mushrooms (sliced), 1/4 cup spinach, 2 tbsp feta cheese, 1 tsp olive oil, salt, pepper, dried herbs', instructions: '1. Whisk egg whites with a pinch of salt and pepper until slightly frothy. 2. Heat olive oil in a non-stick skillet over medium heat. 3. Add bell peppers and mushrooms, sauté 3-4 minutes until softened. 4. Add spinach and stir until wilted, about 1 minute. 5. Pour egg whites evenly over the vegetables. 6. Cook undisturbed 2-3 minutes until edges set. 7. Sprinkle feta cheese on one half, fold omelette over. 8. Cook 1-2 more minutes until set, then serve.', protein_g: 47, carbs_g: 55, fat_g: 20, fiber_g: 11, calories: 588 },
  { id: 17, name: 'Salmon Avocado Rice Bowl', difficulty: 'Easy', equipment: 'stove;pot', ingredients: '6 oz salmon fillet, 1 cup sushi rice, 1/2 avocado (sliced), 1/2 cucumber (sliced), 1 tbsp soy sauce, 1 tsp rice vinegar, 1 tsp sesame seeds, 1 sheet nori (crumbled), pickled ginger (optional), sriracha mayo', instructions: '1. Cook sushi rice according to package directions, season with rice vinegar. 2. Season salmon with salt and pepper. 3. Pan-sear salmon skin-side down in a hot skillet for 4 minutes, flip and cook 3 more minutes. 4. Flake salmon into large chunks. 5. Assemble bowl with rice base, top with salmon, sliced avocado, and cucumber. 6. Drizzle soy sauce and sriracha mayo. 7. Garnish with sesame seeds and crumbled nori.', protein_g: 33, carbs_g: 49, fat_g: 12, fiber_g: 4, calories: 436 },
  { id: 18, name: 'Chicken Caesar Salad', difficulty: 'Easy', equipment: 'stove;pan', ingredients: '6 oz chicken breast, 4 cups romaine lettuce (chopped), 1/4 cup parmesan cheese (shaved), 1/2 cup whole wheat croutons, 2 tbsp Caesar dressing, 1 lemon (juiced), 1 tsp olive oil, salt, pepper', instructions: '1. Season chicken breast with salt, pepper, and olive oil. 2. Grill or pan-sear chicken for 6-7 minutes per side until cooked through. 3. Let chicken rest 5 minutes, then slice. 4. Chop romaine lettuce and place in a large bowl. 5. Add croutons and shaved parmesan. 6. Toss with Caesar dressing and lemon juice. 7. Top with sliced chicken and serve.', protein_g: 21, carbs_g: 48, fat_g: 10, fiber_g: 8, calories: 366 },
  { id: 19, name: 'Lentil Curry', difficulty: 'Easy', equipment: 'stove;pan', ingredients: '1 cup red lentils, 1 can coconut milk (light), 1 can diced tomatoes, 1 onion (diced), 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tsp curry powder, 1 tsp turmeric, 1 tsp cumin, 1 tbsp olive oil, fresh cilantro, salt', instructions: '1. Rinse lentils under cold water. 2. Heat olive oil in a large pot over medium heat. 3. Sauté diced onion for 5 minutes until softened. 4. Add garlic, ginger, curry powder, turmeric, and cumin. Stir for 1 minute until fragrant. 5. Add lentils, diced tomatoes, and coconut milk. Stir to combine. 6. Bring to a boil, then reduce heat and simmer 20-25 minutes until lentils are tender. 7. Season with salt to taste. 8. Serve garnished with fresh cilantro.', protein_g: 50, carbs_g: 31, fat_g: 6, fiber_g: 11, calories: 378 },
  { id: 20, name: 'Chicken Pasta', difficulty: 'Easy', equipment: 'oven;sheet pan', ingredients: '8 oz whole wheat penne, 6 oz chicken breast, 1 cup cherry tomatoes (halved), 2 cups spinach, 3 cloves garlic (minced), 2 tbsp olive oil, 1/4 cup parmesan cheese, Italian seasoning, salt, pepper', instructions: '1. Cook penne according to package directions, reserve 1/2 cup pasta water. 2. Season chicken breast with Italian seasoning, salt, and pepper. 3. Heat 1 tbsp olive oil in a skillet and cook chicken 6-7 minutes per side until done, then slice. 4. In the same pan, add remaining olive oil and sauté garlic for 30 seconds. 5. Add cherry tomatoes and cook 2-3 minutes. 6. Add spinach and stir until wilted. 7. Toss in cooked pasta with a splash of pasta water. 8. Top with sliced chicken and parmesan.', protein_g: 50, carbs_g: 52, fat_g: 18, fiber_g: 5, calories: 570 },
  { id: 21, name: 'Chicken Caesar Salad', difficulty: 'Easy', equipment: 'oven', ingredients: '6 oz chicken breast, 4 cups romaine lettuce (chopped), 1/4 cup parmesan cheese (shaved), 1/2 cup whole wheat croutons, 2 tbsp Caesar dressing, 1 lemon (juiced), 1 tsp olive oil, salt, pepper', instructions: '1. Season chicken breast with salt, pepper, and olive oil. 2. Grill or pan-sear chicken for 6-7 minutes per side until cooked through. 3. Let chicken rest 5 minutes, then slice. 4. Chop romaine lettuce and place in a large bowl. 5. Add croutons and shaved parmesan. 6. Toss with Caesar dressing and lemon juice. 7. Top with sliced chicken and serve.', protein_g: 49, carbs_g: 25, fat_g: 5, fiber_g: 7, calories: 341 },
  { id: 22, name: 'Beef Burrito Bowl', difficulty: 'Easy', equipment: 'stove', ingredients: '6 oz lean ground beef, 1 cup brown rice, 1/2 cup black beans, 1/2 cup corn kernels, 1/4 cup salsa, 1/4 avocado, 2 tbsp sour cream, 1 tsp cumin, 1 tsp chili powder, salt, pepper, lime wedge', instructions: '1. Cook brown rice according to package directions. 2. Season ground beef with cumin, chili powder, salt, and pepper. 3. Cook beef in a skillet over medium-high heat, breaking it up, for 6-8 minutes until browned. 4. Warm black beans and corn in a small saucepan. 5. Build the bowl: rice on the bottom, top with seasoned beef, beans, and corn. 6. Add salsa, sliced avocado, and a dollop of sour cream. 7. Squeeze lime wedge over the top.', protein_g: 25, carbs_g: 34, fat_g: 16, fiber_g: 5, calories: 380 },
  { id: 23, name: 'Lentil Curry', difficulty: 'Easy', equipment: 'blender', ingredients: '1 cup red lentils, 1 can coconut milk (light), 1 can diced tomatoes, 1 onion (diced), 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tsp curry powder, 1 tsp turmeric, 1 tsp cumin, 1 tbsp olive oil, fresh cilantro, salt', instructions: '1. Rinse lentils under cold water. 2. Heat olive oil in a large pot over medium heat. 3. Sauté diced onion for 5 minutes until softened. 4. Add garlic, ginger, curry powder, turmeric, and cumin. Stir for 1 minute until fragrant. 5. Add lentils, diced tomatoes, and coconut milk. Stir to combine. 6. Bring to a boil, then reduce heat and simmer 20-25 minutes until lentils are tender. 7. Season with salt to taste. 8. Serve garnished with fresh cilantro.', protein_g: 39, carbs_g: 20, fat_g: 16, fiber_g: 7, calories: 380 },
  { id: 24, name: 'Tuna Salad Wrap', difficulty: 'Easy', equipment: 'stove', ingredients: '2 cans (5 oz each) tuna in water (drained), 2 large whole wheat tortillas, 2 tbsp Greek yogurt, 1 tbsp Dijon mustard, 1/4 cup celery (diced), 2 tbsp red onion (minced), 1 cup mixed greens, salt, pepper, lemon juice', instructions: '1. Drain tuna and place in a mixing bowl. 2. Add Greek yogurt, Dijon mustard, lemon juice, salt, and pepper. Mix well. 3. Fold in diced celery and red onion. 4. Warm tortillas briefly in a dry skillet or microwave. 5. Lay mixed greens down the center of each tortilla. 6. Spoon tuna mixture over the greens. 7. Fold in the sides and roll tightly into a wrap. 8. Slice in half diagonally and serve.', protein_g: 47, carbs_g: 29, fat_g: 18, fiber_g: 11, calories: 466 },
  { id: 25, name: 'Beef Burrito Bowl', difficulty: 'Easy', equipment: 'stove', ingredients: '6 oz lean ground beef, 1 cup brown rice, 1/2 cup black beans, 1/2 cup corn kernels, 1/4 cup salsa, 1/4 avocado, 2 tbsp sour cream, 1 tsp cumin, 1 tsp chili powder, salt, pepper, lime wedge', instructions: '1. Cook brown rice according to package directions. 2. Season ground beef with cumin, chili powder, salt, and pepper. 3. Cook beef in a skillet over medium-high heat, breaking it up, for 6-8 minutes until browned. 4. Warm black beans and corn in a small saucepan. 5. Build the bowl: rice on the bottom, top with seasoned beef, beans, and corn. 6. Add salsa, sliced avocado, and a dollop of sour cream. 7. Squeeze lime wedge over the top.', protein_g: 28, carbs_g: 26, fat_g: 8, fiber_g: 8, calories: 288 },
  { id: 26, name: 'Egg White Omelette', difficulty: 'Easy', equipment: 'none', ingredients: '6 egg whites, 1/4 cup bell peppers (diced), 1/4 cup mushrooms (sliced), 1/4 cup spinach, 2 tbsp feta cheese, 1 tsp olive oil, salt, pepper, dried herbs', instructions: '1. Whisk egg whites with a pinch of salt and pepper until slightly frothy. 2. Heat olive oil in a non-stick skillet over medium heat. 3. Add bell peppers and mushrooms, sauté 3-4 minutes until softened. 4. Add spinach and stir until wilted, about 1 minute. 5. Pour egg whites evenly over the vegetables. 6. Cook undisturbed 2-3 minutes until edges set. 7. Sprinkle feta cheese on one half, fold omelette over. 8. Cook 1-2 more minutes until set, then serve.', protein_g: 33, carbs_g: 33, fat_g: 5, fiber_g: 5, calories: 309 },
  { id: 27, name: 'Baked Cod with Veggies', difficulty: 'Easy', equipment: 'stove;pot', ingredients: '6 oz cod fillet, 1 cup asparagus (trimmed), 1 cup cherry tomatoes, 1/2 lemon (sliced), 2 tbsp olive oil, 2 cloves garlic (minced), 1 tsp dried oregano, salt, pepper, fresh dill', instructions: '1. Preheat oven to 400°F (200°C). 2. Place cod fillet on a lined baking sheet. 3. Arrange asparagus and cherry tomatoes around the fish. 4. Drizzle everything with olive oil and sprinkle with garlic, oregano, salt, and pepper. 5. Place lemon slices on top of the cod. 6. Bake 15-18 minutes until fish flakes easily with a fork. 7. Garnish with fresh dill and serve.', protein_g: 28, carbs_g: 47, fat_g: 20, fiber_g: 5, calories: 480 },
  { id: 28, name: 'Tofu Veggie Stir Fry', difficulty: 'Easy', equipment: 'oven', ingredients: '14 oz extra-firm tofu (pressed and cubed), 1 cup broccoli florets, 1 red bell pepper (sliced), 1 cup snap peas, 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tbsp soy sauce, 1 tbsp sesame oil, 1 tbsp cornstarch, 1 cup brown rice', instructions: '1. Press tofu for 15 minutes, then cut into cubes and toss with cornstarch. 2. Cook brown rice according to package directions. 3. Heat sesame oil in a wok or large skillet over high heat. 4. Add tofu cubes and cook 5-6 minutes, turning until golden on all sides. Remove and set aside. 5. Add broccoli, bell pepper, and snap peas to the wok. Stir-fry 4-5 minutes. 6. Add garlic and ginger, cook 30 seconds. 7. Return tofu to wok, add soy sauce, and toss everything together. 8. Serve over brown rice.', protein_g: 34, carbs_g: 42, fat_g: 13, fiber_g: 5, calories: 421 },
  { id: 29, name: 'Protein Pancakes', difficulty: 'Easy', equipment: 'oven;sheet pan', ingredients: '1 scoop vanilla protein powder, 1/2 cup oats, 1 banana, 2 egg whites, 1/4 cup unsweetened almond milk, 1/2 tsp baking powder, 1 tsp cinnamon, cooking spray, maple syrup (optional), fresh berries', instructions: '1. Add oats to a blender and pulse into flour. 2. Add protein powder, banana, egg whites, almond milk, baking powder, and cinnamon. Blend until smooth. 3. Let batter rest 5 minutes. 4. Heat a non-stick pan over medium-low heat and spray with cooking spray. 5. Pour about 1/4 cup batter per pancake. 6. Cook 2-3 minutes until bubbles form on surface, then flip. 7. Cook 1-2 more minutes until golden. 8. Serve with fresh berries and a drizzle of maple syrup.', protein_g: 35, carbs_g: 45, fat_g: 17, fiber_g: 6, calories: 473 },
  { id: 30, name: 'Steak Sweet Potato Plate', difficulty: 'Easy', equipment: 'stove;pan', ingredients: '6 oz sirloin steak, 1 medium sweet potato, 1 cup broccoli florets, 1 tbsp olive oil, 1 tsp garlic powder, 1 tsp smoked paprika, salt, pepper, 1 tbsp butter', instructions: '1. Preheat oven to 400°F (200°C). 2. Wash and poke holes in sweet potato. Microwave 5-7 minutes until tender, or bake 45 minutes. 3. Season steak generously with garlic powder, smoked paprika, salt, and pepper. 4. Toss broccoli with olive oil, salt, and pepper. Spread on a baking sheet and roast 15 minutes. 5. Heat a cast-iron skillet over high heat. Sear steak 3-4 minutes per side for medium-rare. 6. Let steak rest 5 minutes, then slice against the grain. 7. Split sweet potato open, add a pat of butter. 8. Plate steak slices alongside sweet potato and roasted broccoli.', protein_g: 42, carbs_g: 34, fat_g: 15, fiber_g: 9, calories: 439 },
  { id: 31, name: 'Tuna Salad Wrap', difficulty: 'Medium', equipment: 'oven', ingredients: '2 cans (5 oz each) tuna in water (drained), 2 large whole wheat tortillas, 2 tbsp Greek yogurt, 1 tbsp Dijon mustard, 1/4 cup celery (diced), 2 tbsp red onion (minced), 1 cup mixed greens, salt, pepper, lemon juice', instructions: '1. Drain tuna and place in a mixing bowl. 2. Add Greek yogurt, Dijon mustard, lemon juice, salt, and pepper. Mix well. 3. Fold in diced celery and red onion. 4. Warm tortillas briefly in a dry skillet or microwave. 5. Lay mixed greens down the center of each tortilla. 6. Spoon tuna mixture over the greens. 7. Fold in the sides and roll tightly into a wrap. 8. Slice in half diagonally and serve.', protein_g: 43, carbs_g: 21, fat_g: 18, fiber_g: 5, calories: 418 },
  { id: 32, name: 'Tofu Veggie Stir Fry', difficulty: 'Medium', equipment: 'oven', ingredients: '14 oz extra-firm tofu (pressed and cubed), 1 cup broccoli florets, 1 red bell pepper (sliced), 1 cup snap peas, 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tbsp soy sauce, 1 tbsp sesame oil, 1 tbsp cornstarch, 1 cup brown rice', instructions: '1. Press tofu for 15 minutes, then cut into cubes and toss with cornstarch. 2. Cook brown rice according to package directions. 3. Heat sesame oil in a wok or large skillet over high heat. 4. Add tofu cubes and cook 5-6 minutes, turning until golden on all sides. Remove and set aside. 5. Add broccoli, bell pepper, and snap peas to the wok. Stir-fry 4-5 minutes. 6. Add garlic and ginger, cook 30 seconds. 7. Return tofu to wok, add soy sauce, and toss everything together. 8. Serve over brown rice.', protein_g: 27, carbs_g: 29, fat_g: 11, fiber_g: 7, calories: 323 },
  { id: 33, name: 'Chicken Caesar Salad', difficulty: 'Medium', equipment: 'stove;pan', ingredients: '6 oz chicken breast, 4 cups romaine lettuce (chopped), 1/4 cup parmesan cheese (shaved), 1/2 cup whole wheat croutons, 2 tbsp Caesar dressing, 1 lemon (juiced), 1 tsp olive oil, salt, pepper', instructions: '1. Season chicken breast with salt, pepper, and olive oil. 2. Grill or pan-sear chicken for 6-7 minutes per side until cooked through. 3. Let chicken rest 5 minutes, then slice. 4. Chop romaine lettuce and place in a large bowl. 5. Add croutons and shaved parmesan. 6. Toss with Caesar dressing and lemon juice. 7. Top with sliced chicken and serve.', protein_g: 20, carbs_g: 44, fat_g: 17, fiber_g: 9, calories: 409 },
  { id: 34, name: 'Lentil Curry', difficulty: 'Medium', equipment: 'blender', ingredients: '1 cup red lentils, 1 can coconut milk (light), 1 can diced tomatoes, 1 onion (diced), 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tsp curry powder, 1 tsp turmeric, 1 tsp cumin, 1 tbsp olive oil, fresh cilantro, salt', instructions: '1. Rinse lentils under cold water. 2. Heat olive oil in a large pot over medium heat. 3. Sauté diced onion for 5 minutes until softened. 4. Add garlic, ginger, curry powder, turmeric, and cumin. Stir for 1 minute until fragrant. 5. Add lentils, diced tomatoes, and coconut milk. Stir to combine. 6. Bring to a boil, then reduce heat and simmer 20-25 minutes until lentils are tender. 7. Season with salt to taste. 8. Serve garnished with fresh cilantro.', protein_g: 35, carbs_g: 41, fat_g: 18, fiber_g: 11, calories: 466 },
  { id: 35, name: 'Quinoa Veggie Bowl', difficulty: 'Medium', equipment: 'none', ingredients: '1 cup quinoa, 1 cup mixed bell peppers (diced), 1 cup zucchini (diced), 1/2 cup black beans, 1/2 avocado, 2 tbsp olive oil, 1 lime (juiced), salt, pepper, cumin', instructions: '1. Cook quinoa according to package directions. 2. Heat olive oil in a pan over medium heat. 3. Sauté bell peppers and zucchini for 5-6 minutes until tender. 4. Drain and rinse black beans. 5. Assemble bowl with quinoa base, top with sautéed veggies and black beans. 6. Slice avocado and place on top. 7. Squeeze lime juice over everything and season with cumin, salt, and pepper.', protein_g: 21, carbs_g: 38, fat_g: 7, fiber_g: 9, calories: 299 },
  { id: 36, name: 'Shrimp Tacos', difficulty: 'Medium', equipment: 'stove;pan', ingredients: '8 oz large shrimp (peeled and deveined), 4 small corn tortillas, 1 cup shredded cabbage, 1/4 cup Greek yogurt, 1 tbsp lime juice, 1 tsp chili powder, 1/2 tsp cumin, 1/2 tsp garlic powder, 1 tbsp olive oil, fresh cilantro, lime wedges', instructions: '1. Season shrimp with chili powder, cumin, garlic powder, salt, and pepper. 2. Heat olive oil in a skillet over medium-high heat. 3. Cook shrimp 2-3 minutes per side until pink and curled. 4. Mix Greek yogurt with lime juice for the crema. 5. Warm corn tortillas in a dry pan or directly over a gas flame. 6. Fill tortillas with shredded cabbage and cooked shrimp. 7. Drizzle with lime crema, top with cilantro, and serve with lime wedges.', protein_g: 46, carbs_g: 50, fat_g: 19, fiber_g: 8, calories: 555 },
  { id: 37, name: 'Protein Pancakes', difficulty: 'Medium', equipment: 'stove;pan', ingredients: '1 scoop vanilla protein powder, 1/2 cup oats, 1 banana, 2 egg whites, 1/4 cup unsweetened almond milk, 1/2 tsp baking powder, 1 tsp cinnamon, cooking spray, maple syrup (optional), fresh berries', instructions: '1. Add oats to a blender and pulse into flour. 2. Add protein powder, banana, egg whites, almond milk, baking powder, and cinnamon. Blend until smooth. 3. Let batter rest 5 minutes. 4. Heat a non-stick pan over medium-low heat and spray with cooking spray. 5. Pour about 1/4 cup batter per pancake. 6. Cook 2-3 minutes until bubbles form on surface, then flip. 7. Cook 1-2 more minutes until golden. 8. Serve with fresh berries and a drizzle of maple syrup.', protein_g: 22, carbs_g: 34, fat_g: 20, fiber_g: 7, calories: 404 },
  { id: 38, name: 'Ground Turkey Lettuce Wraps', difficulty: 'Medium', equipment: 'stove;pot', ingredients: '8 oz lean ground turkey, 8 butter lettuce leaves, 1 tbsp soy sauce, 1 tbsp hoisin sauce, 1 tsp sesame oil, 1 tsp fresh ginger (grated), 2 cloves garlic (minced), 1/4 cup water chestnuts (diced), 2 green onions (sliced), sriracha (optional)', instructions: '1. Heat sesame oil in a skillet over medium-high heat. 2. Add ground turkey and cook 5-6 minutes, breaking it up, until browned. 3. Add garlic and ginger, cook 30 seconds until fragrant. 4. Add soy sauce, hoisin sauce, and diced water chestnuts. Stir 2 minutes. 5. Wash and separate butter lettuce leaves to form cups. 6. Spoon turkey mixture into lettuce cups. 7. Top with sliced green onions and sriracha if desired.', protein_g: 37, carbs_g: 39, fat_g: 12, fiber_g: 8, calories: 412 },
  { id: 39, name: 'Shrimp Tacos', difficulty: 'Medium', equipment: 'stove;pot', ingredients: '8 oz large shrimp (peeled and deveined), 4 small corn tortillas, 1 cup shredded cabbage, 1/4 cup Greek yogurt, 1 tbsp lime juice, 1 tsp chili powder, 1/2 tsp cumin, 1/2 tsp garlic powder, 1 tbsp olive oil, fresh cilantro, lime wedges', instructions: '1. Season shrimp with chili powder, cumin, garlic powder, salt, and pepper. 2. Heat olive oil in a skillet over medium-high heat. 3. Cook shrimp 2-3 minutes per side until pink and curled. 4. Mix Greek yogurt with lime juice for the crema. 5. Warm corn tortillas in a dry pan or directly over a gas flame. 6. Fill tortillas with shredded cabbage and cooked shrimp. 7. Drizzle with lime crema, top with cilantro, and serve with lime wedges.', protein_g: 40, carbs_g: 42, fat_g: 19, fiber_g: 8, calories: 499 },
  { id: 40, name: 'Grilled Chicken Quinoa Bowl', difficulty: 'Medium', equipment: 'none', ingredients: '6 oz chicken breast, 1 cup quinoa, 1 cup cucumber (diced), 1/2 cup cherry tomatoes (halved), 1/4 cup red onion (diced), 2 tbsp lemon juice, 1 tbsp olive oil, fresh parsley, salt, pepper', instructions: '1. Cook quinoa according to package directions and let cool slightly. 2. Season chicken breast with salt, pepper, and olive oil. 3. Grill chicken on medium-high heat for 6-7 minutes per side until internal temp reaches 165°F. 4. Let chicken rest 5 minutes, then slice. 5. Toss quinoa with cucumber, tomatoes, red onion, lemon juice, and parsley. 6. Arrange quinoa mixture in a bowl and top with sliced grilled chicken.', protein_g: 48, carbs_g: 26, fat_g: 17, fiber_g: 4, calories: 449 },
  { id: 41, name: 'Chicken Pasta', difficulty: 'Medium', equipment: 'stove;pot', ingredients: '8 oz whole wheat penne, 6 oz chicken breast, 1 cup cherry tomatoes (halved), 2 cups spinach, 3 cloves garlic (minced), 2 tbsp olive oil, 1/4 cup parmesan cheese, Italian seasoning, salt, pepper', instructions: '1. Cook penne according to package directions, reserve 1/2 cup pasta water. 2. Season chicken breast with Italian seasoning, salt, and pepper. 3. Heat 1 tbsp olive oil in a skillet and cook chicken 6-7 minutes per side until done, then slice. 4. In the same pan, add remaining olive oil and sauté garlic for 30 seconds. 5. Add cherry tomatoes and cook 2-3 minutes. 6. Add spinach and stir until wilted. 7. Toss in cooked pasta with a splash of pasta water. 8. Top with sliced chicken and parmesan.', protein_g: 45, carbs_g: 38, fat_g: 12, fiber_g: 3, calories: 440 },
  { id: 42, name: 'Avocado Toast with Eggs', difficulty: 'Medium', equipment: 'oven;sheet pan', ingredients: '2 slices whole grain bread, 1 ripe avocado, 2 large eggs, 1 tsp lemon juice, red pepper flakes, salt, pepper, everything bagel seasoning (optional)', instructions: '1. Toast bread slices until golden and crispy. 2. While bread toasts, cook eggs to your preference (fried, poached, or scrambled). 3. Halve the avocado, remove pit, and scoop flesh into a bowl. 4. Mash avocado with lemon juice, salt, and pepper. 5. Spread mashed avocado evenly on both toast slices. 6. Top each toast with a cooked egg. 7. Sprinkle with red pepper flakes and everything bagel seasoning if desired.', protein_g: 37, carbs_g: 28, fat_g: 18, fiber_g: 8, calories: 422 },
  { id: 43, name: 'Protein Pancakes', difficulty: 'Medium', equipment: 'oven;sheet pan', ingredients: '1 scoop vanilla protein powder, 1/2 cup oats, 1 banana, 2 egg whites, 1/4 cup unsweetened almond milk, 1/2 tsp baking powder, 1 tsp cinnamon, cooking spray, maple syrup (optional), fresh berries', instructions: '1. Add oats to a blender and pulse into flour. 2. Add protein powder, banana, egg whites, almond milk, baking powder, and cinnamon. Blend until smooth. 3. Let batter rest 5 minutes. 4. Heat a non-stick pan over medium-low heat and spray with cooking spray. 5. Pour about 1/4 cup batter per pancake. 6. Cook 2-3 minutes until bubbles form on surface, then flip. 7. Cook 1-2 more minutes until golden. 8. Serve with fresh berries and a drizzle of maple syrup.', protein_g: 24, carbs_g: 40, fat_g: 13, fiber_g: 10, calories: 373 },
  { id: 44, name: 'Protein Smoothie', difficulty: 'Medium', equipment: 'oven;sheet pan', ingredients: '1 scoop whey protein powder (vanilla or chocolate), 1 banana, 1 cup unsweetened almond milk, 1 tbsp peanut butter, 1/2 cup frozen berries, 1 handful spinach, 1/2 cup ice', instructions: '1. Add almond milk and spinach to blender, blend until smooth. 2. Add banana, frozen berries, and peanut butter. 3. Add protein powder and ice. 4. Blend on high for 60-90 seconds until creamy and smooth. 5. Pour into a glass and serve immediately.', protein_g: 38, carbs_g: 26, fat_g: 15, fiber_g: 5, calories: 391 },
  { id: 45, name: 'Avocado Toast with Eggs', difficulty: 'Medium', equipment: 'stove', ingredients: '2 slices whole grain bread, 1 ripe avocado, 2 large eggs, 1 tsp lemon juice, red pepper flakes, salt, pepper, everything bagel seasoning (optional)', instructions: '1. Toast bread slices until golden and crispy. 2. While bread toasts, cook eggs to your preference (fried, poached, or scrambled). 3. Halve the avocado, remove pit, and scoop flesh into a bowl. 4. Mash avocado with lemon juice, salt, and pepper. 5. Spread mashed avocado evenly on both toast slices. 6. Top each toast with a cooked egg. 7. Sprinkle with red pepper flakes and everything bagel seasoning if desired.', protein_g: 31, carbs_g: 33, fat_g: 9, fiber_g: 12, calories: 337 },
  { id: 46, name: 'Ground Turkey Lettuce Wraps', difficulty: 'Medium', equipment: 'oven', ingredients: '8 oz lean ground turkey, 8 butter lettuce leaves, 1 tbsp soy sauce, 1 tbsp hoisin sauce, 1 tsp sesame oil, 1 tsp fresh ginger (grated), 2 cloves garlic (minced), 1/4 cup water chestnuts (diced), 2 green onions (sliced), sriracha (optional)', instructions: '1. Heat sesame oil in a skillet over medium-high heat. 2. Add ground turkey and cook 5-6 minutes, breaking it up, until browned. 3. Add garlic and ginger, cook 30 seconds until fragrant. 4. Add soy sauce, hoisin sauce, and diced water chestnuts. Stir 2 minutes. 5. Wash and separate butter lettuce leaves to form cups. 6. Spoon turkey mixture into lettuce cups. 7. Top with sliced green onions and sriracha if desired.', protein_g: 39, carbs_g: 52, fat_g: 12, fiber_g: 7, calories: 472 },
  { id: 47, name: 'Tuna Salad Wrap', difficulty: 'Medium', equipment: 'stove;pan', ingredients: '2 cans (5 oz each) tuna in water (drained), 2 large whole wheat tortillas, 2 tbsp Greek yogurt, 1 tbsp Dijon mustard, 1/4 cup celery (diced), 2 tbsp red onion (minced), 1 cup mixed greens, salt, pepper, lemon juice', instructions: '1. Drain tuna and place in a mixing bowl. 2. Add Greek yogurt, Dijon mustard, lemon juice, salt, and pepper. Mix well. 3. Fold in diced celery and red onion. 4. Warm tortillas briefly in a dry skillet or microwave. 5. Lay mixed greens down the center of each tortilla. 6. Spoon tuna mixture over the greens. 7. Fold in the sides and roll tightly into a wrap. 8. Slice in half diagonally and serve.', protein_g: 29, carbs_g: 34, fat_g: 18, fiber_g: 3, calories: 414 },
  { id: 48, name: 'Turkey Chili', difficulty: 'Medium', equipment: 'stove', ingredients: '1 lb lean ground turkey, 1 can kidney beans (drained), 1 can diced tomatoes, 1 onion (diced), 1 bell pepper (diced), 3 cloves garlic (minced), 2 tbsp chili powder, 1 tsp cumin, 1 tsp smoked paprika, 1 tbsp olive oil, salt, pepper, sour cream for topping', instructions: '1. Heat olive oil in a large pot over medium-high heat. 2. Add diced onion and bell pepper, cook 5 minutes until softened. 3. Add ground turkey and cook 6-8 minutes until browned, breaking it apart. 4. Add garlic, chili powder, cumin, and smoked paprika. Stir 1 minute. 5. Pour in diced tomatoes and kidney beans. 6. Bring to a boil, then reduce heat and simmer 25-30 minutes, stirring occasionally. 7. Season with salt and pepper. 8. Serve topped with a dollop of sour cream.', protein_g: 25, carbs_g: 34, fat_g: 10, fiber_g: 5, calories: 326 },
  { id: 49, name: 'Quinoa Veggie Bowl', difficulty: 'Medium', equipment: 'stove;pan', ingredients: '1 cup quinoa, 1 cup mixed bell peppers (diced), 1 cup zucchini (diced), 1/2 cup black beans, 1/2 avocado, 2 tbsp olive oil, 1 lime (juiced), salt, pepper, cumin', instructions: '1. Cook quinoa according to package directions. 2. Heat olive oil in a pan over medium heat. 3. Sauté bell peppers and zucchini for 5-6 minutes until tender. 4. Drain and rinse black beans. 5. Assemble bowl with quinoa base, top with sautéed veggies and black beans. 6. Slice avocado and place on top. 7. Squeeze lime juice over everything and season with cumin, salt, and pepper.', protein_g: 41, carbs_g: 55, fat_g: 8, fiber_g: 7, calories: 456 },
  { id: 50, name: 'Beef Burrito Bowl', difficulty: 'Medium', equipment: 'stove;pot', ingredients: '6 oz lean ground beef, 1 cup brown rice, 1/2 cup black beans, 1/2 cup corn kernels, 1/4 cup salsa, 1/4 avocado, 2 tbsp sour cream, 1 tsp cumin, 1 tsp chili powder, salt, pepper, lime wedge', instructions: '1. Cook brown rice according to package directions. 2. Season ground beef with cumin, chili powder, salt, and pepper. 3. Cook beef in a skillet over medium-high heat, breaking it up, for 6-8 minutes until browned. 4. Warm black beans and corn in a small saucepan. 5. Build the bowl: rice on the bottom, top with seasoned beef, beans, and corn. 6. Add salsa, sliced avocado, and a dollop of sour cream. 7. Squeeze lime wedge over the top.', protein_g: 43, carbs_g: 40, fat_g: 19, fiber_g: 5, calories: 503 },
  { id: 51, name: 'Salmon Avocado Rice Bowl', difficulty: 'Medium', equipment: 'stove;pan', ingredients: '6 oz salmon fillet, 1 cup sushi rice, 1/2 avocado (sliced), 1/2 cucumber (sliced), 1 tbsp soy sauce, 1 tsp rice vinegar, 1 tsp sesame seeds, 1 sheet nori (crumbled), pickled ginger (optional), sriracha mayo', instructions: '1. Cook sushi rice according to package directions, season with rice vinegar. 2. Season salmon with salt and pepper. 3. Pan-sear salmon skin-side down in a hot skillet for 4 minutes, flip and cook 3 more minutes. 4. Flake salmon into large chunks. 5. Assemble bowl with rice base, top with salmon, sliced avocado, and cucumber. 6. Drizzle soy sauce and sriracha mayo. 7. Garnish with sesame seeds and crumbled nori.', protein_g: 31, carbs_g: 46, fat_g: 19, fiber_g: 5, calories: 479 },
  { id: 52, name: 'Avocado Toast with Eggs', difficulty: 'Medium', equipment: 'blender', ingredients: '2 slices whole grain bread, 1 ripe avocado, 2 large eggs, 1 tsp lemon juice, red pepper flakes, salt, pepper, everything bagel seasoning (optional)', instructions: '1. Toast bread slices until golden and crispy. 2. While bread toasts, cook eggs to your preference (fried, poached, or scrambled). 3. Halve the avocado, remove pit, and scoop flesh into a bowl. 4. Mash avocado with lemon juice, salt, and pepper. 5. Spread mashed avocado evenly on both toast slices. 6. Top each toast with a cooked egg. 7. Sprinkle with red pepper flakes and everything bagel seasoning if desired.', protein_g: 40, carbs_g: 54, fat_g: 7, fiber_g: 3, calories: 439 },
  { id: 53, name: 'Chicken Stir Fry', difficulty: 'Medium', equipment: 'stove;pot', ingredients: '6 oz chicken breast (sliced thin), 1 cup broccoli florets, 1 red bell pepper (sliced), 1/2 cup snap peas, 2 cloves garlic (minced), 1 tbsp soy sauce, 1 tbsp oyster sauce, 1 tsp sesame oil, 1 tsp cornstarch, 1 cup jasmine rice', instructions: '1. Cook jasmine rice according to package directions. 2. Slice chicken thin and toss with cornstarch, salt, and pepper. 3. Heat sesame oil in a wok or large skillet over high heat. 4. Add chicken and stir-fry 4-5 minutes until cooked through. Remove and set aside. 5. Add broccoli, bell pepper, and snap peas. Stir-fry 3-4 minutes until crisp-tender. 6. Add garlic, cook 30 seconds. 7. Return chicken to wok, add soy sauce and oyster sauce. Toss to combine. 8. Serve over jasmine rice.', protein_g: 41, carbs_g: 54, fat_g: 20, fiber_g: 7, calories: 560 },
  { id: 54, name: 'Protein Smoothie', difficulty: 'Medium', equipment: 'stove;pot', ingredients: '1 scoop whey protein powder (vanilla or chocolate), 1 banana, 1 cup unsweetened almond milk, 1 tbsp peanut butter, 1/2 cup frozen berries, 1 handful spinach, 1/2 cup ice', instructions: '1. Add almond milk and spinach to blender, blend until smooth. 2. Add banana, frozen berries, and peanut butter. 3. Add protein powder and ice. 4. Blend on high for 60-90 seconds until creamy and smooth. 5. Pour into a glass and serve immediately.', protein_g: 40, carbs_g: 26, fat_g: 13, fiber_g: 6, calories: 381 },
  { id: 55, name: 'Protein Pancakes', difficulty: 'Medium', equipment: 'blender', ingredients: '1 scoop vanilla protein powder, 1/2 cup oats, 1 banana, 2 egg whites, 1/4 cup unsweetened almond milk, 1/2 tsp baking powder, 1 tsp cinnamon, cooking spray, maple syrup (optional), fresh berries', instructions: '1. Add oats to a blender and pulse into flour. 2. Add protein powder, banana, egg whites, almond milk, baking powder, and cinnamon. Blend until smooth. 3. Let batter rest 5 minutes. 4. Heat a non-stick pan over medium-low heat and spray with cooking spray. 5. Pour about 1/4 cup batter per pancake. 6. Cook 2-3 minutes until bubbles form on surface, then flip. 7. Cook 1-2 more minutes until golden. 8. Serve with fresh berries and a drizzle of maple syrup.', protein_g: 50, carbs_g: 56, fat_g: 11, fiber_g: 12, calories: 523 },
  { id: 56, name: 'Avocado Toast with Eggs', difficulty: 'Medium', equipment: 'stove;pan', ingredients: '2 slices whole grain bread, 1 ripe avocado, 2 large eggs, 1 tsp lemon juice, red pepper flakes, salt, pepper, everything bagel seasoning (optional)', instructions: '1. Toast bread slices until golden and crispy. 2. While bread toasts, cook eggs to your preference (fried, poached, or scrambled). 3. Halve the avocado, remove pit, and scoop flesh into a bowl. 4. Mash avocado with lemon juice, salt, and pepper. 5. Spread mashed avocado evenly on both toast slices. 6. Top each toast with a cooked egg. 7. Sprinkle with red pepper flakes and everything bagel seasoning if desired.', protein_g: 46, carbs_g: 34, fat_g: 13, fiber_g: 10, calories: 437 },
  { id: 57, name: 'Chicken Stir Fry', difficulty: 'Medium', equipment: 'oven;sheet pan', ingredients: '6 oz chicken breast (sliced thin), 1 cup broccoli florets, 1 red bell pepper (sliced), 1/2 cup snap peas, 2 cloves garlic (minced), 1 tbsp soy sauce, 1 tbsp oyster sauce, 1 tsp sesame oil, 1 tsp cornstarch, 1 cup jasmine rice', instructions: '1. Cook jasmine rice according to package directions. 2. Slice chicken thin and toss with cornstarch, salt, and pepper. 3. Heat sesame oil in a wok or large skillet over high heat. 4. Add chicken and stir-fry 4-5 minutes until cooked through. Remove and set aside. 5. Add broccoli, bell pepper, and snap peas. Stir-fry 3-4 minutes until crisp-tender. 6. Add garlic, cook 30 seconds. 7. Return chicken to wok, add soy sauce and oyster sauce. Toss to combine. 8. Serve over jasmine rice.', protein_g: 28, carbs_g: 49, fat_g: 10, fiber_g: 4, calories: 398 },
  { id: 58, name: 'Steak Sweet Potato Plate', difficulty: 'Medium', equipment: 'blender', ingredients: '6 oz sirloin steak, 1 medium sweet potato, 1 cup broccoli florets, 1 tbsp olive oil, 1 tsp garlic powder, 1 tsp smoked paprika, salt, pepper, 1 tbsp butter', instructions: '1. Preheat oven to 400°F (200°C). 2. Wash and poke holes in sweet potato. Microwave 5-7 minutes until tender, or bake 45 minutes. 3. Season steak generously with garlic powder, smoked paprika, salt, and pepper. 4. Toss broccoli with olive oil, salt, and pepper. Spread on a baking sheet and roast 15 minutes. 5. Heat a cast-iron skillet over high heat. Sear steak 3-4 minutes per side for medium-rare. 6. Let steak rest 5 minutes, then slice against the grain. 7. Split sweet potato open, add a pat of butter. 8. Plate steak slices alongside sweet potato and roasted broccoli.', protein_g: 36, carbs_g: 49, fat_g: 8, fiber_g: 4, calories: 412 },
  { id: 59, name: 'Greek Yogurt Parfait', difficulty: 'Medium', equipment: 'blender', ingredients: '1 cup plain Greek yogurt, 1/3 cup granola, 1/2 cup mixed berries (blueberries, strawberries, raspberries), 1 tbsp honey, 1 tbsp chia seeds, 1 tbsp almond butter', instructions: '1. Spoon half the Greek yogurt into a glass or bowl. 2. Add a layer of half the mixed berries. 3. Sprinkle half the granola over the berries. 4. Repeat layers with remaining yogurt, berries, and granola. 5. Drizzle honey over the top. 6. Add chia seeds and a dollop of almond butter. 7. Serve immediately or refrigerate up to 4 hours.', protein_g: 25, carbs_g: 26, fat_g: 15, fiber_g: 12, calories: 339 },
  { id: 60, name: 'Steak Sweet Potato Plate', difficulty: 'Medium', equipment: 'stove', ingredients: '6 oz sirloin steak, 1 medium sweet potato, 1 cup broccoli florets, 1 tbsp olive oil, 1 tsp garlic powder, 1 tsp smoked paprika, salt, pepper, 1 tbsp butter', instructions: '1. Preheat oven to 400°F (200°C). 2. Wash and poke holes in sweet potato. Microwave 5-7 minutes until tender, or bake 45 minutes. 3. Season steak generously with garlic powder, smoked paprika, salt, and pepper. 4. Toss broccoli with olive oil, salt, and pepper. Spread on a baking sheet and roast 15 minutes. 5. Heat a cast-iron skillet over high heat. Sear steak 3-4 minutes per side for medium-rare. 6. Let steak rest 5 minutes, then slice against the grain. 7. Split sweet potato open, add a pat of butter. 8. Plate steak slices alongside sweet potato and roasted broccoli.', protein_g: 43, carbs_g: 42, fat_g: 10, fiber_g: 4, calories: 430 },
  { id: 61, name: 'Lentil Curry', difficulty: 'Medium', equipment: 'stove', ingredients: '1 cup red lentils, 1 can coconut milk (light), 1 can diced tomatoes, 1 onion (diced), 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tsp curry powder, 1 tsp turmeric, 1 tsp cumin, 1 tbsp olive oil, fresh cilantro, salt', instructions: '1. Rinse lentils under cold water. 2. Heat olive oil in a large pot over medium heat. 3. Sauté diced onion for 5 minutes until softened. 4. Add garlic, ginger, curry powder, turmeric, and cumin. Stir for 1 minute until fragrant. 5. Add lentils, diced tomatoes, and coconut milk. Stir to combine. 6. Bring to a boil, then reduce heat and simmer 20-25 minutes until lentils are tender. 7. Season with salt to taste. 8. Serve garnished with fresh cilantro.', protein_g: 48, carbs_g: 57, fat_g: 10, fiber_g: 7, calories: 510 },
  { id: 62, name: 'Turkey Chili', difficulty: 'Medium', equipment: 'none', ingredients: '1 lb lean ground turkey, 1 can kidney beans (drained), 1 can diced tomatoes, 1 onion (diced), 1 bell pepper (diced), 3 cloves garlic (minced), 2 tbsp chili powder, 1 tsp cumin, 1 tsp smoked paprika, 1 tbsp olive oil, salt, pepper, sour cream for topping', instructions: '1. Heat olive oil in a large pot over medium-high heat. 2. Add diced onion and bell pepper, cook 5 minutes until softened. 3. Add ground turkey and cook 6-8 minutes until browned, breaking it apart. 4. Add garlic, chili powder, cumin, and smoked paprika. Stir 1 minute. 5. Pour in diced tomatoes and kidney beans. 6. Bring to a boil, then reduce heat and simmer 25-30 minutes, stirring occasionally. 7. Season with salt and pepper. 8. Serve topped with a dollop of sour cream.', protein_g: 29, carbs_g: 29, fat_g: 15, fiber_g: 7, calories: 367 },
  { id: 63, name: 'Chicken Pasta', difficulty: 'Medium', equipment: 'oven', ingredients: '8 oz whole wheat penne, 6 oz chicken breast, 1 cup cherry tomatoes (halved), 2 cups spinach, 3 cloves garlic (minced), 2 tbsp olive oil, 1/4 cup parmesan cheese, Italian seasoning, salt, pepper', instructions: '1. Cook penne according to package directions, reserve 1/2 cup pasta water. 2. Season chicken breast with Italian seasoning, salt, and pepper. 3. Heat 1 tbsp olive oil in a skillet and cook chicken 6-7 minutes per side until done, then slice. 4. In the same pan, add remaining olive oil and sauté garlic for 30 seconds. 5. Add cherry tomatoes and cook 2-3 minutes. 6. Add spinach and stir until wilted. 7. Toss in cooked pasta with a splash of pasta water. 8. Top with sliced chicken and parmesan.', protein_g: 34, carbs_g: 47, fat_g: 15, fiber_g: 3, calories: 459 },
  { id: 64, name: 'Greek Yogurt Parfait', difficulty: 'Medium', equipment: 'blender', ingredients: '1 cup plain Greek yogurt, 1/3 cup granola, 1/2 cup mixed berries (blueberries, strawberries, raspberries), 1 tbsp honey, 1 tbsp chia seeds, 1 tbsp almond butter', instructions: '1. Spoon half the Greek yogurt into a glass or bowl. 2. Add a layer of half the mixed berries. 3. Sprinkle half the granola over the berries. 4. Repeat layers with remaining yogurt, berries, and granola. 5. Drizzle honey over the top. 6. Add chia seeds and a dollop of almond butter. 7. Serve immediately or refrigerate up to 4 hours.', protein_g: 41, carbs_g: 60, fat_g: 5, fiber_g: 8, calories: 449 },
  { id: 65, name: 'Ground Turkey Lettuce Wraps', difficulty: 'Medium', equipment: 'none', ingredients: '8 oz lean ground turkey, 8 butter lettuce leaves, 1 tbsp soy sauce, 1 tbsp hoisin sauce, 1 tsp sesame oil, 1 tsp fresh ginger (grated), 2 cloves garlic (minced), 1/4 cup water chestnuts (diced), 2 green onions (sliced), sriracha (optional)', instructions: '1. Heat sesame oil in a skillet over medium-high heat. 2. Add ground turkey and cook 5-6 minutes, breaking it up, until browned. 3. Add garlic and ginger, cook 30 seconds until fragrant. 4. Add soy sauce, hoisin sauce, and diced water chestnuts. Stir 2 minutes. 5. Wash and separate butter lettuce leaves to form cups. 6. Spoon turkey mixture into lettuce cups. 7. Top with sliced green onions and sriracha if desired.', protein_g: 37, carbs_g: 36, fat_g: 7, fiber_g: 11, calories: 355 },
  { id: 66, name: 'Quinoa Veggie Bowl', difficulty: 'Medium', equipment: 'oven;sheet pan', ingredients: '1 cup quinoa, 1 cup mixed bell peppers (diced), 1 cup zucchini (diced), 1/2 cup black beans, 1/2 avocado, 2 tbsp olive oil, 1 lime (juiced), salt, pepper, cumin', instructions: '1. Cook quinoa according to package directions. 2. Heat olive oil in a pan over medium heat. 3. Sauté bell peppers and zucchini for 5-6 minutes until tender. 4. Drain and rinse black beans. 5. Assemble bowl with quinoa base, top with sautéed veggies and black beans. 6. Slice avocado and place on top. 7. Squeeze lime juice over everything and season with cumin, salt, and pepper.', protein_g: 33, carbs_g: 50, fat_g: 13, fiber_g: 4, calories: 449 },
  { id: 67, name: 'Greek Yogurt Parfait', difficulty: 'Medium', equipment: 'oven;sheet pan', ingredients: '1 cup plain Greek yogurt, 1/3 cup granola, 1/2 cup mixed berries (blueberries, strawberries, raspberries), 1 tbsp honey, 1 tbsp chia seeds, 1 tbsp almond butter', instructions: '1. Spoon half the Greek yogurt into a glass or bowl. 2. Add a layer of half the mixed berries. 3. Sprinkle half the granola over the berries. 4. Repeat layers with remaining yogurt, berries, and granola. 5. Drizzle honey over the top. 6. Add chia seeds and a dollop of almond butter. 7. Serve immediately or refrigerate up to 4 hours.', protein_g: 49, carbs_g: 35, fat_g: 15, fiber_g: 6, calories: 471 },
  { id: 68, name: 'Steak Sweet Potato Plate', difficulty: 'Medium', equipment: 'stove', ingredients: '6 oz sirloin steak, 1 medium sweet potato, 1 cup broccoli florets, 1 tbsp olive oil, 1 tsp garlic powder, 1 tsp smoked paprika, salt, pepper, 1 tbsp butter', instructions: '1. Preheat oven to 400°F (200°C). 2. Wash and poke holes in sweet potato. Microwave 5-7 minutes until tender, or bake 45 minutes. 3. Season steak generously with garlic powder, smoked paprika, salt, and pepper. 4. Toss broccoli with olive oil, salt, and pepper. Spread on a baking sheet and roast 15 minutes. 5. Heat a cast-iron skillet over high heat. Sear steak 3-4 minutes per side for medium-rare. 6. Let steak rest 5 minutes, then slice against the grain. 7. Split sweet potato open, add a pat of butter. 8. Plate steak slices alongside sweet potato and roasted broccoli.', protein_g: 20, carbs_g: 45, fat_g: 12, fiber_g: 8, calories: 368 },
  { id: 69, name: 'Beef Burrito Bowl', difficulty: 'Medium', equipment: 'oven;sheet pan', ingredients: '6 oz lean ground beef, 1 cup brown rice, 1/2 cup black beans, 1/2 cup corn kernels, 1/4 cup salsa, 1/4 avocado, 2 tbsp sour cream, 1 tsp cumin, 1 tsp chili powder, salt, pepper, lime wedge', instructions: '1. Cook brown rice according to package directions. 2. Season ground beef with cumin, chili powder, salt, and pepper. 3. Cook beef in a skillet over medium-high heat, breaking it up, for 6-8 minutes until browned. 4. Warm black beans and corn in a small saucepan. 5. Build the bowl: rice on the bottom, top with seasoned beef, beans, and corn. 6. Add salsa, sliced avocado, and a dollop of sour cream. 7. Squeeze lime wedge over the top.', protein_g: 25, carbs_g: 24, fat_g: 13, fiber_g: 11, calories: 313 },
  { id: 70, name: 'Egg White Omelette', difficulty: 'Medium', equipment: 'stove;pan', ingredients: '6 egg whites, 1/4 cup bell peppers (diced), 1/4 cup mushrooms (sliced), 1/4 cup spinach, 2 tbsp feta cheese, 1 tsp olive oil, salt, pepper, dried herbs', instructions: '1. Whisk egg whites with a pinch of salt and pepper until slightly frothy. 2. Heat olive oil in a non-stick skillet over medium heat. 3. Add bell peppers and mushrooms, sauté 3-4 minutes until softened. 4. Add spinach and stir until wilted, about 1 minute. 5. Pour egg whites evenly over the vegetables. 6. Cook undisturbed 2-3 minutes until edges set. 7. Sprinkle feta cheese on one half, fold omelette over. 8. Cook 1-2 more minutes until set, then serve.', protein_g: 24, carbs_g: 21, fat_g: 10, fiber_g: 7, calories: 270 },
  { id: 71, name: 'Steak Sweet Potato Plate', difficulty: 'Hard', equipment: 'blender', ingredients: '6 oz sirloin steak, 1 medium sweet potato, 1 cup broccoli florets, 1 tbsp olive oil, 1 tsp garlic powder, 1 tsp smoked paprika, salt, pepper, 1 tbsp butter', instructions: '1. Preheat oven to 400°F (200°C). 2. Wash and poke holes in sweet potato. Microwave 5-7 minutes until tender, or bake 45 minutes. 3. Season steak generously with garlic powder, smoked paprika, salt, and pepper. 4. Toss broccoli with olive oil, salt, and pepper. Spread on a baking sheet and roast 15 minutes. 5. Heat a cast-iron skillet over high heat. Sear steak 3-4 minutes per side for medium-rare. 6. Let steak rest 5 minutes, then slice against the grain. 7. Split sweet potato open, add a pat of butter. 8. Plate steak slices alongside sweet potato and roasted broccoli.', protein_g: 24, carbs_g: 32, fat_g: 20, fiber_g: 5, calories: 404 },
  { id: 72, name: 'Tuna Salad Wrap', difficulty: 'Hard', equipment: 'blender', ingredients: '2 cans (5 oz each) tuna in water (drained), 2 large whole wheat tortillas, 2 tbsp Greek yogurt, 1 tbsp Dijon mustard, 1/4 cup celery (diced), 2 tbsp red onion (minced), 1 cup mixed greens, salt, pepper, lemon juice', instructions: '1. Drain tuna and place in a mixing bowl. 2. Add Greek yogurt, Dijon mustard, lemon juice, salt, and pepper. Mix well. 3. Fold in diced celery and red onion. 4. Warm tortillas briefly in a dry skillet or microwave. 5. Lay mixed greens down the center of each tortilla. 6. Spoon tuna mixture over the greens. 7. Fold in the sides and roll tightly into a wrap. 8. Slice in half diagonally and serve.', protein_g: 42, carbs_g: 21, fat_g: 18, fiber_g: 12, calories: 414 },
  { id: 73, name: 'Grilled Chicken Quinoa Bowl', difficulty: 'Hard', equipment: 'blender', ingredients: '6 oz chicken breast, 1 cup quinoa, 1 cup cucumber (diced), 1/2 cup cherry tomatoes (halved), 1/4 cup red onion (diced), 2 tbsp lemon juice, 1 tbsp olive oil, fresh parsley, salt, pepper', instructions: '1. Cook quinoa according to package directions and let cool slightly. 2. Season chicken breast with salt, pepper, and olive oil. 3. Grill chicken on medium-high heat for 6-7 minutes per side until internal temp reaches 165°F. 4. Let chicken rest 5 minutes, then slice. 5. Toss quinoa with cucumber, tomatoes, red onion, lemon juice, and parsley. 6. Arrange quinoa mixture in a bowl and top with sliced grilled chicken.', protein_g: 41, carbs_g: 27, fat_g: 17, fiber_g: 11, calories: 425 },
  { id: 74, name: 'Grilled Chicken Quinoa Bowl', difficulty: 'Hard', equipment: 'stove;pan', ingredients: '6 oz chicken breast, 1 cup quinoa, 1 cup cucumber (diced), 1/2 cup cherry tomatoes (halved), 1/4 cup red onion (diced), 2 tbsp lemon juice, 1 tbsp olive oil, fresh parsley, salt, pepper', instructions: '1. Cook quinoa according to package directions and let cool slightly. 2. Season chicken breast with salt, pepper, and olive oil. 3. Grill chicken on medium-high heat for 6-7 minutes per side until internal temp reaches 165°F. 4. Let chicken rest 5 minutes, then slice. 5. Toss quinoa with cucumber, tomatoes, red onion, lemon juice, and parsley. 6. Arrange quinoa mixture in a bowl and top with sliced grilled chicken.', protein_g: 30, carbs_g: 57, fat_g: 5, fiber_g: 4, calories: 393 },
  { id: 75, name: 'Chicken Caesar Salad', difficulty: 'Hard', equipment: 'stove;pan', ingredients: '6 oz chicken breast, 4 cups romaine lettuce (chopped), 1/4 cup parmesan cheese (shaved), 1/2 cup whole wheat croutons, 2 tbsp Caesar dressing, 1 lemon (juiced), 1 tsp olive oil, salt, pepper', instructions: '1. Season chicken breast with salt, pepper, and olive oil. 2. Grill or pan-sear chicken for 6-7 minutes per side until cooked through. 3. Let chicken rest 5 minutes, then slice. 4. Chop romaine lettuce and place in a large bowl. 5. Add croutons and shaved parmesan. 6. Toss with Caesar dressing and lemon juice. 7. Top with sliced chicken and serve.', protein_g: 33, carbs_g: 53, fat_g: 13, fiber_g: 8, calories: 461 },
  { id: 76, name: 'Tofu Veggie Stir Fry', difficulty: 'Hard', equipment: 'stove;pan', ingredients: '14 oz extra-firm tofu (pressed and cubed), 1 cup broccoli florets, 1 red bell pepper (sliced), 1 cup snap peas, 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tbsp soy sauce, 1 tbsp sesame oil, 1 tbsp cornstarch, 1 cup brown rice', instructions: '1. Press tofu for 15 minutes, then cut into cubes and toss with cornstarch. 2. Cook brown rice according to package directions. 3. Heat sesame oil in a wok or large skillet over high heat. 4. Add tofu cubes and cook 5-6 minutes, turning until golden on all sides. Remove and set aside. 5. Add broccoli, bell pepper, and snap peas to the wok. Stir-fry 4-5 minutes. 6. Add garlic and ginger, cook 30 seconds. 7. Return tofu to wok, add soy sauce, and toss everything together. 8. Serve over brown rice.', protein_g: 45, carbs_g: 54, fat_g: 5, fiber_g: 7, calories: 441 },
  { id: 77, name: 'Tuna Salad Wrap', difficulty: 'Hard', equipment: 'oven;sheet pan', ingredients: '2 cans (5 oz each) tuna in water (drained), 2 large whole wheat tortillas, 2 tbsp Greek yogurt, 1 tbsp Dijon mustard, 1/4 cup celery (diced), 2 tbsp red onion (minced), 1 cup mixed greens, salt, pepper, lemon juice', instructions: '1. Drain tuna and place in a mixing bowl. 2. Add Greek yogurt, Dijon mustard, lemon juice, salt, and pepper. Mix well. 3. Fold in diced celery and red onion. 4. Warm tortillas briefly in a dry skillet or microwave. 5. Lay mixed greens down the center of each tortilla. 6. Spoon tuna mixture over the greens. 7. Fold in the sides and roll tightly into a wrap. 8. Slice in half diagonally and serve.', protein_g: 41, carbs_g: 23, fat_g: 11, fiber_g: 6, calories: 355 },
  { id: 78, name: 'Avocado Toast with Eggs', difficulty: 'Hard', equipment: 'stove', ingredients: '2 slices whole grain bread, 1 ripe avocado, 2 large eggs, 1 tsp lemon juice, red pepper flakes, salt, pepper, everything bagel seasoning (optional)', instructions: '1. Toast bread slices until golden and crispy. 2. While bread toasts, cook eggs to your preference (fried, poached, or scrambled). 3. Halve the avocado, remove pit, and scoop flesh into a bowl. 4. Mash avocado with lemon juice, salt, and pepper. 5. Spread mashed avocado evenly on both toast slices. 6. Top each toast with a cooked egg. 7. Sprinkle with red pepper flakes and everything bagel seasoning if desired.', protein_g: 43, carbs_g: 20, fat_g: 20, fiber_g: 11, calories: 432 },
  { id: 79, name: 'Lentil Curry', difficulty: 'Hard', equipment: 'stove', ingredients: '1 cup red lentils, 1 can coconut milk (light), 1 can diced tomatoes, 1 onion (diced), 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tsp curry powder, 1 tsp turmeric, 1 tsp cumin, 1 tbsp olive oil, fresh cilantro, salt', instructions: '1. Rinse lentils under cold water. 2. Heat olive oil in a large pot over medium heat. 3. Sauté diced onion for 5 minutes until softened. 4. Add garlic, ginger, curry powder, turmeric, and cumin. Stir for 1 minute until fragrant. 5. Add lentils, diced tomatoes, and coconut milk. Stir to combine. 6. Bring to a boil, then reduce heat and simmer 20-25 minutes until lentils are tender. 7. Season with salt to taste. 8. Serve garnished with fresh cilantro.', protein_g: 42, carbs_g: 34, fat_g: 9, fiber_g: 11, calories: 385 },
  { id: 80, name: 'Chicken Caesar Salad', difficulty: 'Hard', equipment: 'none', ingredients: '6 oz chicken breast, 4 cups romaine lettuce (chopped), 1/4 cup parmesan cheese (shaved), 1/2 cup whole wheat croutons, 2 tbsp Caesar dressing, 1 lemon (juiced), 1 tsp olive oil, salt, pepper', instructions: '1. Season chicken breast with salt, pepper, and olive oil. 2. Grill or pan-sear chicken for 6-7 minutes per side until cooked through. 3. Let chicken rest 5 minutes, then slice. 4. Chop romaine lettuce and place in a large bowl. 5. Add croutons and shaved parmesan. 6. Toss with Caesar dressing and lemon juice. 7. Top with sliced chicken and serve.', protein_g: 41, carbs_g: 52, fat_g: 11, fiber_g: 7, calories: 471 },
  { id: 81, name: 'Lentil Curry', difficulty: 'Hard', equipment: 'oven;sheet pan', ingredients: '1 cup red lentils, 1 can coconut milk (light), 1 can diced tomatoes, 1 onion (diced), 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tsp curry powder, 1 tsp turmeric, 1 tsp cumin, 1 tbsp olive oil, fresh cilantro, salt', instructions: '1. Rinse lentils under cold water. 2. Heat olive oil in a large pot over medium heat. 3. Sauté diced onion for 5 minutes until softened. 4. Add garlic, ginger, curry powder, turmeric, and cumin. Stir for 1 minute until fragrant. 5. Add lentils, diced tomatoes, and coconut milk. Stir to combine. 6. Bring to a boil, then reduce heat and simmer 20-25 minutes until lentils are tender. 7. Season with salt to taste. 8. Serve garnished with fresh cilantro.', protein_g: 22, carbs_g: 29, fat_g: 12, fiber_g: 8, calories: 312 },
  { id: 82, name: 'Baked Cod with Veggies', difficulty: 'Hard', equipment: 'none', ingredients: '6 oz cod fillet, 1 cup asparagus (trimmed), 1 cup cherry tomatoes, 1/2 lemon (sliced), 2 tbsp olive oil, 2 cloves garlic (minced), 1 tsp dried oregano, salt, pepper, fresh dill', instructions: '1. Preheat oven to 400°F (200°C). 2. Place cod fillet on a lined baking sheet. 3. Arrange asparagus and cherry tomatoes around the fish. 4. Drizzle everything with olive oil and sprinkle with garlic, oregano, salt, and pepper. 5. Place lemon slices on top of the cod. 6. Bake 15-18 minutes until fish flakes easily with a fork. 7. Garnish with fresh dill and serve.', protein_g: 35, carbs_g: 33, fat_g: 13, fiber_g: 11, calories: 389 },
  { id: 83, name: 'Lentil Curry', difficulty: 'Hard', equipment: 'oven', ingredients: '1 cup red lentils, 1 can coconut milk (light), 1 can diced tomatoes, 1 onion (diced), 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tsp curry powder, 1 tsp turmeric, 1 tsp cumin, 1 tbsp olive oil, fresh cilantro, salt', instructions: '1. Rinse lentils under cold water. 2. Heat olive oil in a large pot over medium heat. 3. Sauté diced onion for 5 minutes until softened. 4. Add garlic, ginger, curry powder, turmeric, and cumin. Stir for 1 minute until fragrant. 5. Add lentils, diced tomatoes, and coconut milk. Stir to combine. 6. Bring to a boil, then reduce heat and simmer 20-25 minutes until lentils are tender. 7. Season with salt to taste. 8. Serve garnished with fresh cilantro.', protein_g: 38, carbs_g: 24, fat_g: 20, fiber_g: 11, calories: 428 },
  { id: 84, name: 'Protein Pancakes', difficulty: 'Hard', equipment: 'stove', ingredients: '1 scoop vanilla protein powder, 1/2 cup oats, 1 banana, 2 egg whites, 1/4 cup unsweetened almond milk, 1/2 tsp baking powder, 1 tsp cinnamon, cooking spray, maple syrup (optional), fresh berries', instructions: '1. Add oats to a blender and pulse into flour. 2. Add protein powder, banana, egg whites, almond milk, baking powder, and cinnamon. Blend until smooth. 3. Let batter rest 5 minutes. 4. Heat a non-stick pan over medium-low heat and spray with cooking spray. 5. Pour about 1/4 cup batter per pancake. 6. Cook 2-3 minutes until bubbles form on surface, then flip. 7. Cook 1-2 more minutes until golden. 8. Serve with fresh berries and a drizzle of maple syrup.', protein_g: 20, carbs_g: 48, fat_g: 10, fiber_g: 10, calories: 362 },
  { id: 85, name: 'Steak Sweet Potato Plate', difficulty: 'Hard', equipment: 'stove;pot', ingredients: '6 oz sirloin steak, 1 medium sweet potato, 1 cup broccoli florets, 1 tbsp olive oil, 1 tsp garlic powder, 1 tsp smoked paprika, salt, pepper, 1 tbsp butter', instructions: '1. Preheat oven to 400°F (200°C). 2. Wash and poke holes in sweet potato. Microwave 5-7 minutes until tender, or bake 45 minutes. 3. Season steak generously with garlic powder, smoked paprika, salt, and pepper. 4. Toss broccoli with olive oil, salt, and pepper. Spread on a baking sheet and roast 15 minutes. 5. Heat a cast-iron skillet over high heat. Sear steak 3-4 minutes per side for medium-rare. 6. Let steak rest 5 minutes, then slice against the grain. 7. Split sweet potato open, add a pat of butter. 8. Plate steak slices alongside sweet potato and roasted broccoli.', protein_g: 48, carbs_g: 33, fat_g: 8, fiber_g: 6, calories: 396 },
  { id: 86, name: 'Steak Sweet Potato Plate', difficulty: 'Hard', equipment: 'none', ingredients: '6 oz sirloin steak, 1 medium sweet potato, 1 cup broccoli florets, 1 tbsp olive oil, 1 tsp garlic powder, 1 tsp smoked paprika, salt, pepper, 1 tbsp butter', instructions: '1. Preheat oven to 400°F (200°C). 2. Wash and poke holes in sweet potato. Microwave 5-7 minutes until tender, or bake 45 minutes. 3. Season steak generously with garlic powder, smoked paprika, salt, and pepper. 4. Toss broccoli with olive oil, salt, and pepper. Spread on a baking sheet and roast 15 minutes. 5. Heat a cast-iron skillet over high heat. Sear steak 3-4 minutes per side for medium-rare. 6. Let steak rest 5 minutes, then slice against the grain. 7. Split sweet potato open, add a pat of butter. 8. Plate steak slices alongside sweet potato and roasted broccoli.', protein_g: 30, carbs_g: 21, fat_g: 8, fiber_g: 5, calories: 276 },
  { id: 87, name: 'Salmon Avocado Rice Bowl', difficulty: 'Hard', equipment: 'oven', ingredients: '6 oz salmon fillet, 1 cup sushi rice, 1/2 avocado (sliced), 1/2 cucumber (sliced), 1 tbsp soy sauce, 1 tsp rice vinegar, 1 tsp sesame seeds, 1 sheet nori (crumbled), pickled ginger (optional), sriracha mayo', instructions: '1. Cook sushi rice according to package directions, season with rice vinegar. 2. Season salmon with salt and pepper. 3. Pan-sear salmon skin-side down in a hot skillet for 4 minutes, flip and cook 3 more minutes. 4. Flake salmon into large chunks. 5. Assemble bowl with rice base, top with salmon, sliced avocado, and cucumber. 6. Drizzle soy sauce and sriracha mayo. 7. Garnish with sesame seeds and crumbled nori.', protein_g: 33, carbs_g: 44, fat_g: 13, fiber_g: 8, calories: 425 },
  { id: 88, name: 'Avocado Toast with Eggs', difficulty: 'Hard', equipment: 'stove;pot', ingredients: '2 slices whole grain bread, 1 ripe avocado, 2 large eggs, 1 tsp lemon juice, red pepper flakes, salt, pepper, everything bagel seasoning (optional)', instructions: '1. Toast bread slices until golden and crispy. 2. While bread toasts, cook eggs to your preference (fried, poached, or scrambled). 3. Halve the avocado, remove pit, and scoop flesh into a bowl. 4. Mash avocado with lemon juice, salt, and pepper. 5. Spread mashed avocado evenly on both toast slices. 6. Top each toast with a cooked egg. 7. Sprinkle with red pepper flakes and everything bagel seasoning if desired.', protein_g: 44, carbs_g: 31, fat_g: 14, fiber_g: 4, calories: 426 },
  { id: 89, name: 'Beef Burrito Bowl', difficulty: 'Hard', equipment: 'oven', ingredients: '6 oz lean ground beef, 1 cup brown rice, 1/2 cup black beans, 1/2 cup corn kernels, 1/4 cup salsa, 1/4 avocado, 2 tbsp sour cream, 1 tsp cumin, 1 tsp chili powder, salt, pepper, lime wedge', instructions: '1. Cook brown rice according to package directions. 2. Season ground beef with cumin, chili powder, salt, and pepper. 3. Cook beef in a skillet over medium-high heat, breaking it up, for 6-8 minutes until browned. 4. Warm black beans and corn in a small saucepan. 5. Build the bowl: rice on the bottom, top with seasoned beef, beans, and corn. 6. Add salsa, sliced avocado, and a dollop of sour cream. 7. Squeeze lime wedge over the top.', protein_g: 35, carbs_g: 29, fat_g: 7, fiber_g: 12, calories: 319 },
  { id: 90, name: 'Tuna Salad Wrap', difficulty: 'Hard', equipment: 'stove;pan', ingredients: '2 cans (5 oz each) tuna in water (drained), 2 large whole wheat tortillas, 2 tbsp Greek yogurt, 1 tbsp Dijon mustard, 1/4 cup celery (diced), 2 tbsp red onion (minced), 1 cup mixed greens, salt, pepper, lemon juice', instructions: '1. Drain tuna and place in a mixing bowl. 2. Add Greek yogurt, Dijon mustard, lemon juice, salt, and pepper. Mix well. 3. Fold in diced celery and red onion. 4. Warm tortillas briefly in a dry skillet or microwave. 5. Lay mixed greens down the center of each tortilla. 6. Spoon tuna mixture over the greens. 7. Fold in the sides and roll tightly into a wrap. 8. Slice in half diagonally and serve.', protein_g: 31, carbs_g: 30, fat_g: 5, fiber_g: 8, calories: 289 },
  { id: 91, name: 'Chicken Caesar Salad', difficulty: 'Hard', equipment: 'none', ingredients: '6 oz chicken breast, 4 cups romaine lettuce (chopped), 1/4 cup parmesan cheese (shaved), 1/2 cup whole wheat croutons, 2 tbsp Caesar dressing, 1 lemon (juiced), 1 tsp olive oil, salt, pepper', instructions: '1. Season chicken breast with salt, pepper, and olive oil. 2. Grill or pan-sear chicken for 6-7 minutes per side until cooked through. 3. Let chicken rest 5 minutes, then slice. 4. Chop romaine lettuce and place in a large bowl. 5. Add croutons and shaved parmesan. 6. Toss with Caesar dressing and lemon juice. 7. Top with sliced chicken and serve.', protein_g: 22, carbs_g: 33, fat_g: 8, fiber_g: 8, calories: 292 },
  { id: 92, name: 'Tofu Veggie Stir Fry', difficulty: 'Hard', equipment: 'oven;sheet pan', ingredients: '14 oz extra-firm tofu (pressed and cubed), 1 cup broccoli florets, 1 red bell pepper (sliced), 1 cup snap peas, 3 cloves garlic (minced), 1 tbsp fresh ginger (grated), 2 tbsp soy sauce, 1 tbsp sesame oil, 1 tbsp cornstarch, 1 cup brown rice', instructions: '1. Press tofu for 15 minutes, then cut into cubes and toss with cornstarch. 2. Cook brown rice according to package directions. 3. Heat sesame oil in a wok or large skillet over high heat. 4. Add tofu cubes and cook 5-6 minutes, turning until golden on all sides. Remove and set aside. 5. Add broccoli, bell pepper, and snap peas to the wok. Stir-fry 4-5 minutes. 6. Add garlic and ginger, cook 30 seconds. 7. Return tofu to wok, add soy sauce, and toss everything together. 8. Serve over brown rice.', protein_g: 26, carbs_g: 50, fat_g: 17, fiber_g: 6, calories: 457 },
  { id: 93, name: 'Tuna Salad Wrap', difficulty: 'Hard', equipment: 'stove;pan', ingredients: '2 cans (5 oz each) tuna in water (drained), 2 large whole wheat tortillas, 2 tbsp Greek yogurt, 1 tbsp Dijon mustard, 1/4 cup celery (diced), 2 tbsp red onion (minced), 1 cup mixed greens, salt, pepper, lemon juice', instructions: '1. Drain tuna and place in a mixing bowl. 2. Add Greek yogurt, Dijon mustard, lemon juice, salt, and pepper. Mix well. 3. Fold in diced celery and red onion. 4. Warm tortillas briefly in a dry skillet or microwave. 5. Lay mixed greens down the center of each tortilla. 6. Spoon tuna mixture over the greens. 7. Fold in the sides and roll tightly into a wrap. 8. Slice in half diagonally and serve.', protein_g: 29, carbs_g: 32, fat_g: 14, fiber_g: 11, calories: 370 },
  { id: 94, name: 'Salmon Avocado Rice Bowl', difficulty: 'Hard', equipment: 'oven;sheet pan', ingredients: '6 oz salmon fillet, 1 cup sushi rice, 1/2 avocado (sliced), 1/2 cucumber (sliced), 1 tbsp soy sauce, 1 tsp rice vinegar, 1 tsp sesame seeds, 1 sheet nori (crumbled), pickled ginger (optional), sriracha mayo', instructions: '1. Cook sushi rice according to package directions, season with rice vinegar. 2. Season salmon with salt and pepper. 3. Pan-sear salmon skin-side down in a hot skillet for 4 minutes, flip and cook 3 more minutes. 4. Flake salmon into large chunks. 5. Assemble bowl with rice base, top with salmon, sliced avocado, and cucumber. 6. Drizzle soy sauce and sriracha mayo. 7. Garnish with sesame seeds and crumbled nori.', protein_g: 45, carbs_g: 60, fat_g: 12, fiber_g: 11, calories: 528 },
  { id: 95, name: 'Quinoa Veggie Bowl', difficulty: 'Hard', equipment: 'oven', ingredients: '1 cup quinoa, 1 cup mixed bell peppers (diced), 1 cup zucchini (diced), 1/2 cup black beans, 1/2 avocado, 2 tbsp olive oil, 1 lime (juiced), salt, pepper, cumin', instructions: '1. Cook quinoa according to package directions. 2. Heat olive oil in a pan over medium heat. 3. Sauté bell peppers and zucchini for 5-6 minutes until tender. 4. Drain and rinse black beans. 5. Assemble bowl with quinoa base, top with sautéed veggies and black beans. 6. Slice avocado and place on top. 7. Squeeze lime juice over everything and season with cumin, salt, and pepper.', protein_g: 36, carbs_g: 53, fat_g: 17, fiber_g: 7, calories: 509 },
  { id: 96, name: 'Grilled Chicken Quinoa Bowl', difficulty: 'Hard', equipment: 'stove', ingredients: '6 oz chicken breast, 1 cup quinoa, 1 cup cucumber (diced), 1/2 cup cherry tomatoes (halved), 1/4 cup red onion (diced), 2 tbsp lemon juice, 1 tbsp olive oil, fresh parsley, salt, pepper', instructions: '1. Cook quinoa according to package directions and let cool slightly. 2. Season chicken breast with salt, pepper, and olive oil. 3. Grill chicken on medium-high heat for 6-7 minutes per side until internal temp reaches 165°F. 4. Let chicken rest 5 minutes, then slice. 5. Toss quinoa with cucumber, tomatoes, red onion, lemon juice, and parsley. 6. Arrange quinoa mixture in a bowl and top with sliced grilled chicken.', protein_g: 48, carbs_g: 30, fat_g: 17, fiber_g: 6, calories: 465 },
  { id: 97, name: 'Salmon Avocado Rice Bowl', difficulty: 'Hard', equipment: 'stove', ingredients: '6 oz salmon fillet, 1 cup sushi rice, 1/2 avocado (sliced), 1/2 cucumber (sliced), 1 tbsp soy sauce, 1 tsp rice vinegar, 1 tsp sesame seeds, 1 sheet nori (crumbled), pickled ginger (optional), sriracha mayo', instructions: '1. Cook sushi rice according to package directions, season with rice vinegar. 2. Season salmon with salt and pepper. 3. Pan-sear salmon skin-side down in a hot skillet for 4 minutes, flip and cook 3 more minutes. 4. Flake salmon into large chunks. 5. Assemble bowl with rice base, top with salmon, sliced avocado, and cucumber. 6. Drizzle soy sauce and sriracha mayo. 7. Garnish with sesame seeds and crumbled nori.', protein_g: 47, carbs_g: 53, fat_g: 17, fiber_g: 12, calories: 553 },
  { id: 98, name: 'Protein Pancakes', difficulty: 'Hard', equipment: 'oven', ingredients: '1 scoop vanilla protein powder, 1/2 cup oats, 1 banana, 2 egg whites, 1/4 cup unsweetened almond milk, 1/2 tsp baking powder, 1 tsp cinnamon, cooking spray, maple syrup (optional), fresh berries', instructions: '1. Add oats to a blender and pulse into flour. 2. Add protein powder, banana, egg whites, almond milk, baking powder, and cinnamon. Blend until smooth. 3. Let batter rest 5 minutes. 4. Heat a non-stick pan over medium-low heat and spray with cooking spray. 5. Pour about 1/4 cup batter per pancake. 6. Cook 2-3 minutes until bubbles form on surface, then flip. 7. Cook 1-2 more minutes until golden. 8. Serve with fresh berries and a drizzle of maple syrup.', protein_g: 44, carbs_g: 26, fat_g: 14, fiber_g: 11, calories: 406 },
  { id: 99, name: 'Grilled Chicken Quinoa Bowl', difficulty: 'Hard', equipment: 'oven;sheet pan', ingredients: '6 oz chicken breast, 1 cup quinoa, 1 cup cucumber (diced), 1/2 cup cherry tomatoes (halved), 1/4 cup red onion (diced), 2 tbsp lemon juice, 1 tbsp olive oil, fresh parsley, salt, pepper', instructions: '1. Cook quinoa according to package directions and let cool slightly. 2. Season chicken breast with salt, pepper, and olive oil. 3. Grill chicken on medium-high heat for 6-7 minutes per side until internal temp reaches 165°F. 4. Let chicken rest 5 minutes, then slice. 5. Toss quinoa with cucumber, tomatoes, red onion, lemon juice, and parsley. 6. Arrange quinoa mixture in a bowl and top with sliced grilled chicken.', protein_g: 50, carbs_g: 37, fat_g: 6, fiber_g: 4, calories: 402 },
  { id: 100, name: 'Greek Yogurt Parfait', difficulty: 'Hard', equipment: 'stove;pan', ingredients: '1 cup plain Greek yogurt, 1/3 cup granola, 1/2 cup mixed berries (blueberries, strawberries, raspberries), 1 tbsp honey, 1 tbsp chia seeds, 1 tbsp almond butter', instructions: '1. Spoon half the Greek yogurt into a glass or bowl. 2. Add a layer of half the mixed berries. 3. Sprinkle half the granola over the berries. 4. Repeat layers with remaining yogurt, berries, and granola. 5. Drizzle honey over the top. 6. Add chia seeds and a dollop of almond butter. 7. Serve immediately or refrigerate up to 4 hours.', protein_g: 38, carbs_g: 48, fat_g: 9, fiber_g: 6, calories: 425 },
];

// ── Transform to RecipeEntry[] ──────────────────────────────────────

function parseEquipment(raw: string): string[] {
  if (!raw || raw === 'none') return [];
  return raw.split(';').map((s) => s.trim()).filter(Boolean);
}

function parseIngredients(raw: string): string[] {
  return raw.split(',').map((s) => s.trim()).filter(Boolean);
}

function parseInstructions(raw: string): string[] {
  // Split on "N. " pattern
  return raw
    .split(/\d+\.\s+/)
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Returns the 100 seed recipes as RecipeEntry[].
 * De-duplicates by base recipe name — when multiple CSV rows share the
 * same base name (e.g. "Chicken Pasta 2", "Chicken Pasta 12"), we keep
 * only the first occurrence per unique base name per difficulty tier.
 * This gives us one Easy, one Medium, and one Hard variant of each recipe.
 */
export function getSeedRecipes(): RecipeEntry[] {
  const now = new Date().toISOString();
  const seen = new Set<string>();

  return RAW_RECIPES
    .filter((row) => {
      // De-dup: keep first occurrence per base-name + difficulty
      const key = `${row.name}__${row.difficulty}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .map((row) => {
      const equipment = parseEquipment(row.equipment);
      const ingredientsList = parseIngredients(row.ingredients);
      const instructions = parseInstructions(row.instructions);

      const recipe: RecipeEntry = {
        id: `seed_recipe_${row.id}`,
        userId: 'local_user',
        name: row.name,
        description: `${row.difficulty} · ${row.calories} cal · ${equipment.length ? equipment.join(', ') : 'No special equipment'}`,
        items: [{
          id: `seed_ri_${row.id}`,
          name: row.name,
          calories: row.calories,
          protein_g: row.protein_g,
          carbs_g: row.carbs_g,
          fat_g: row.fat_g,
          fiber_g: row.fiber_g,
          quantity: 1,
          unit: 'serving',
          is_estimate: false,
        }],
        servings: 1,
        createdAt: now,
        updatedAt: now,
        // Extended metadata
        source: 'seed',
        difficulty: row.difficulty,
        equipment,
        ingredientsList,
        instructions,
        calories: row.calories,
        protein_g: row.protein_g,
        carbs_g: row.carbs_g,
        fat_g: row.fat_g,
        fiber_g: row.fiber_g,
      };

      return recipe;
    });
}

/**
 * Get the set of all seed recipe IDs for merge detection.
 */
export function getSeedRecipeIds(): Set<string> {
  return new Set(RAW_RECIPES.map((r) => `seed_recipe_${r.id}`));
}
